CREATE TABLE car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19,2) NOT NULL );
INSERT INTO car (id, make, model, price) VALUES (1, 'BMW', 'M3', '8.85');
INSERT INTO car (id, make, model, price) VALUES (2, 'Mercury', 'Sable', '8.01');
INSERT INTO car (id, make, model, price) VALUES (3, 'Mercury', 'Grand Marquis', '7.58');
INSERT INTO car (id, make, model, price) VALUES (4, 'Toyota', 'Corolla', '8.97');
INSERT INTO car (id, make, model, price) VALUES (5, 'Suzuki', 'Aerio', '2.89');
INSERT INTO car (id, make, model, price) VALUES (6, 'Chevrolet', 'Silverado', '9.69');
INSERT INTO car (id, make, model, price) VALUES (7, 'Ford', 'Thunderbird', '8.77');
INSERT INTO car (id, make, model, price) VALUES (8, 'Volkswagen', 'New Beetle', '2.67');
INSERT INTO car (id, make, model, price) VALUES (9, 'Ford', 'Freestar', '5.71');
INSERT INTO car (id, make, model, price) VALUES (10, 'GMC', 'Sierra 2500', '1.50');
INSERT INTO car (id, make, model, price) VALUES (11, 'Porsche', '911', '6.44');
INSERT INTO car (id, make, model, price) VALUES (12, 'Ford', 'Escort', '2.93');
INSERT INTO car (id, make, model, price) VALUES (13, 'Chevrolet', 'Suburban 1500', '0.95');
INSERT INTO car (id, make, model, price) VALUES (14, 'Nissan', 'Frontier', '7.19');
INSERT INTO car (id, make, model, price) VALUES (15, 'Dodge', 'Nitro', '0.94');
INSERT INTO car (id, make, model, price) VALUES (16, 'Bentley', 'Mulsanne', '7.02');
INSERT INTO car (id, make, model, price) VALUES (17, 'Suzuki', 'XL-7', '4.69');
INSERT INTO car (id, make, model, price) VALUES (18, 'Chevrolet', 'S10', '6.37');
INSERT INTO car (id, make, model, price) VALUES (19, 'Ford', 'Mustang', '4.56');
INSERT INTO car (id, make, model, price) VALUES (20, 'Subaru', 'Alcyone SVX', '4.38');
INSERT INTO car (id, make, model, price) VALUES (21, 'BMW', '330', '4.70');
INSERT INTO car (id, make, model, price) VALUES (22, 'BMW', 'X5', '8.96');
INSERT INTO car (id, make, model, price) VALUES (23, 'Toyota', 'Celica', '6.44');
INSERT INTO car (id, make, model, price) VALUES (24, 'Ford', 'Expedition EL', '3.06');
INSERT INTO car (id, make, model, price) VALUES (25, 'Toyota', 'Land Cruiser', '9.42');
INSERT INTO car (id, make, model, price) VALUES (26, 'Acura', 'RL', '9.33');
INSERT INTO car (id, make, model, price) VALUES (27, 'Buick', 'Verano', '2.58');
INSERT INTO car (id, make, model, price) VALUES (28, 'Suzuki', 'XL-7', '0.52');
INSERT INTO car (id, make, model, price) VALUES (29, 'Kia', 'Forte', '8.96');
INSERT INTO car (id, make, model, price) VALUES (30, 'Chevrolet', 'Suburban', '2.57');
INSERT INTO car (id, make, model, price) VALUES (31, 'Mazda', '323', '3.76');
INSERT INTO car (id, make, model, price) VALUES (32, 'GMC', '3500 Club Coupe', '2.56');
INSERT INTO car (id, make, model, price) VALUES (33, 'Mitsubishi', 'Truck', '7.13');
INSERT INTO car (id, make, model, price) VALUES (34, 'Suzuki', 'Grand Vitara', '5.10');
INSERT INTO car (id, make, model, price) VALUES (35, 'Buick', 'LeSabre', '6.88');
INSERT INTO car (id, make, model, price) VALUES (36, 'Chevrolet', 'Traverse', '2.91');
INSERT INTO car (id, make, model, price) VALUES (37, 'Mercedes-Benz', 'CLK-Class', '4.05');
INSERT INTO car (id, make, model, price) VALUES (38, 'Chrysler', 'Sebring', '7.45');
INSERT INTO car (id, make, model, price) VALUES (39, 'Chevrolet', 'G-Series 3500', '0.89');
INSERT INTO car (id, make, model, price) VALUES (40, 'BMW', 'M5', '7.21');
INSERT INTO car (id, make, model, price) VALUES (41, 'Chrysler', 'Concorde', '2.74');
INSERT INTO car (id, make, model, price) VALUES (42, 'Chevrolet', 'Express', '5.78');
INSERT INTO car (id, make, model, price) VALUES (43, 'Cadillac', 'CTS', '5.41');
INSERT INTO car (id, make, model, price) VALUES (44, 'Hyundai', 'Azera', '6.07');
INSERT INTO car (id, make, model, price) VALUES (45, 'Buick', 'Century', '7.31');
INSERT INTO car (id, make, model, price) VALUES (46, 'Dodge', 'Ram 1500', '0.19');
INSERT INTO car (id, make, model, price) VALUES (47, 'Lincoln', 'Navigator', '2.32');
INSERT INTO car (id, make, model, price) VALUES (48, 'Ford', 'Tempo', '6.58');
INSERT INTO car (id, make, model, price) VALUES (49, 'Dodge', 'Ram 2500 Club', '9.47');
INSERT INTO car (id, make, model, price) VALUES (50, 'Cadillac', 'Escalade', '7.78');
INSERT INTO car (id, make, model, price) VALUES (51, 'Ford', 'Laser', '6.18');
INSERT INTO car (id, make, model, price) VALUES (52, 'Hummer', 'H1', '3.71');
INSERT INTO car (id, make, model, price) VALUES (53, 'Lexus', 'RX', '0.78');
INSERT INTO car (id, make, model, price) VALUES (54, 'Rambler', 'Classic', '7.61');
INSERT INTO car (id, make, model, price) VALUES (55, 'Acura', 'ZDX', '5.57');
INSERT INTO car (id, make, model, price) VALUES (56, 'Mazda', 'RX-7', '4.36');
INSERT INTO car (id, make, model, price) VALUES (57, 'Hummer', 'H1', '3.58');
INSERT INTO car (id, make, model, price) VALUES (58, 'Buick', 'Coachbuilder', '1.10');
INSERT INTO car (id, make, model, price) VALUES (59, 'Mitsubishi', 'Montero', '9.74');
INSERT INTO car (id, make, model, price) VALUES (60, 'Chevrolet', 'Camaro', '4.84');
INSERT INTO car (id, make, model, price) VALUES (61, 'Jaguar', 'XK', '2.81');
INSERT INTO car (id, make, model, price) VALUES (62, 'BMW', '7 Series', '6.34');
INSERT INTO car (id, make, model, price) VALUES (63, 'GMC', '2500', '3.73');
INSERT INTO car (id, make, model, price) VALUES (64, 'Cadillac', 'Seville', '6.92');
INSERT INTO car (id, make, model, price) VALUES (65, 'BMW', '3 Series', '1.67');
INSERT INTO car (id, make, model, price) VALUES (66, 'Chevrolet', 'Blazer', '7.77');
INSERT INTO car (id, make, model, price) VALUES (67, 'Chevrolet', '1500', '8.71');
INSERT INTO car (id, make, model, price) VALUES (68, 'GMC', 'Savana 3500', '4.53');
INSERT INTO car (id, make, model, price) VALUES (69, 'Ford', 'Crown Victoria', '3.77');
INSERT INTO car (id, make, model, price) VALUES (70, 'Mazda', 'Mazdaspeed 3', '3.15');
INSERT INTO car (id, make, model, price) VALUES (71, 'Nissan', 'Rogue', '6.37');
INSERT INTO car (id, make, model, price) VALUES (72, 'Chevrolet', 'Prizm', '9.42');
INSERT INTO car (id, make, model, price) VALUES (73, 'Suzuki', 'Sidekick', '0.84');
INSERT INTO car (id, make, model, price) VALUES (74, 'Saab', '9000', '3.17');
INSERT INTO car (id, make, model, price) VALUES (75, 'Maybach', '57', '0.42');
INSERT INTO car (id, make, model, price) VALUES (76, 'Aptera', 'Type-1h', '6.73');
INSERT INTO car (id, make, model, price) VALUES (77, 'Ford', 'Ranger', '3.24');
INSERT INTO car (id, make, model, price) VALUES (78, 'Pontiac', 'Grand Prix', '4.47');
INSERT INTO car (id, make, model, price) VALUES (79, 'BMW', '5 Series', '0.98');
INSERT INTO car (id, make, model, price) VALUES (80, 'Mazda', 'Mazda3', '6.44');
INSERT INTO car (id, make, model, price) VALUES (81, 'Suzuki', 'SJ', '3.13');
INSERT INTO car (id, make, model, price) VALUES (82, 'Toyota', 'Camry', '1.80');
INSERT INTO car (id, make, model, price) VALUES (83, 'GMC', '1500 Club Coupe', '7.43');
INSERT INTO car (id, make, model, price) VALUES (84, 'Cadillac', 'XLR', '8.46');
INSERT INTO car (id, make, model, price) VALUES (85, 'Kia', 'Rio5', '6.95');
INSERT INTO car (id, make, model, price) VALUES (86, 'Mitsubishi', 'Pajero', '2.91');
INSERT INTO car (id, make, model, price) VALUES (87, 'Chrysler', 'Sebring', '6.06');
INSERT INTO car (id, make, model, price) VALUES (88, 'Chevrolet', 'Express 3500', '9.73');
INSERT INTO car (id, make, model, price) VALUES (89, 'Saab', '9-3', '0.74');
INSERT INTO car (id, make, model, price) VALUES (90, 'Jeep', 'Wrangler', '3.87');
INSERT INTO car (id, make, model, price) VALUES (91, 'Jaguar', 'XJ Series', '5.63');
INSERT INTO car (id, make, model, price) VALUES (92, 'Chevrolet', 'Tahoe', '6.75');
INSERT INTO car (id, make, model, price) VALUES (93, 'Dodge', 'D250 Club', '2.53');
INSERT INTO car (id, make, model, price) VALUES (94, 'GMC', 'Savana 2500', '5.30');
INSERT INTO car (id, make, model, price) VALUES (95, 'GMC', 'Envoy XUV', '1.15');
INSERT INTO car (id, make, model, price) VALUES (96, 'Toyota', 'Tercel', '1.66');
INSERT INTO car (id, make, model, price) VALUES (97, 'Mitsubishi', 'Galant', '7.32');
INSERT INTO car (id, make, model, price) VALUES (98, 'Chevrolet', 'Cobalt SS', '6.99');
INSERT INTO car (id, make, model, price) VALUES (99, 'BMW', '525', '7.19');
INSERT INTO car (id, make, model, price) VALUES (100, 'Ford', 'Tempo', '8.19');
INSERT INTO car (id, make, model, price) VALUES (101, 'Chevrolet', 'Astro', '4.19');
INSERT INTO car (id, make, model, price) VALUES (102, 'Hyundai', 'Elantra', '5.10');
INSERT INTO car (id, make, model, price) VALUES (103, 'Subaru', 'Loyale', '3.43');
INSERT INTO car (id, make, model, price) VALUES (104, 'Mercury', 'Mountaineer', '0.15');
INSERT INTO car (id, make, model, price) VALUES (105, 'Chrysler', '200', '9.40');
INSERT INTO car (id, make, model, price) VALUES (106, 'Nissan', 'Armada', '9.56');
INSERT INTO car (id, make, model, price) VALUES (107, 'GMC', 'Sierra', '9.15');
INSERT INTO car (id, make, model, price) VALUES (108, 'Nissan', 'Quest', '2.53');
INSERT INTO car (id, make, model, price) VALUES (109, 'Saturn', 'Ion', '4.77');
INSERT INTO car (id, make, model, price) VALUES (110, 'Mercedes-Benz', 'G-Class', '0.16');
INSERT INTO car (id, make, model, price) VALUES (111, 'Toyota', 'Land Cruiser', '3.41');
INSERT INTO car (id, make, model, price) VALUES (112, 'Buick', 'Riviera', '9.51');
INSERT INTO car (id, make, model, price) VALUES (113, 'Audi', 'R8', '9.54');
INSERT INTO car (id, make, model, price) VALUES (114, 'Mazda', 'MX-6', '2.21');
INSERT INTO car (id, make, model, price) VALUES (115, 'Pontiac', 'GTO', '5.57');
INSERT INTO car (id, make, model, price) VALUES (116, 'Scion', 'xB', '7.65');
INSERT INTO car (id, make, model, price) VALUES (117, 'Ferrari', '599 GTB Fiorano', '6.84');
INSERT INTO car (id, make, model, price) VALUES (118, 'Ford', 'Econoline E250', '2.12');
INSERT INTO car (id, make, model, price) VALUES (119, 'Acura', 'SLX', '4.46');
INSERT INTO car (id, make, model, price) VALUES (120, 'Ford', 'Escort', '8.36');
INSERT INTO car (id, make, model, price) VALUES (121, 'Buick', 'Rainier', '8.50');
INSERT INTO car (id, make, model, price) VALUES (122, 'Cadillac', 'DeVille', '4.21');
INSERT INTO car (id, make, model, price) VALUES (123, 'Hyundai', 'XG350', '3.13');
INSERT INTO car (id, make, model, price) VALUES (124, 'Mazda', 'Miata MX-5', '8.52');
INSERT INTO car (id, make, model, price) VALUES (125, 'Honda', 'Insight', '9.54');
INSERT INTO car (id, make, model, price) VALUES (126, 'Mazda', 'MPV', '1.84');
INSERT INTO car (id, make, model, price) VALUES (127, 'Mercedes-Benz', '500SL', '4.83');
INSERT INTO car (id, make, model, price) VALUES (128, 'Chrysler', 'Pacifica', '0.37');
INSERT INTO car (id, make, model, price) VALUES (129, 'Mazda', 'Mazdaspeed 3', '3.25');
INSERT INTO car (id, make, model, price) VALUES (130, 'Cadillac', 'Escalade', '7.59');
INSERT INTO car (id, make, model, price) VALUES (131, 'Infiniti', 'Q', '1.15');
INSERT INTO car (id, make, model, price) VALUES (132, 'Ford', 'F-Series', '4.88');
INSERT INTO car (id, make, model, price) VALUES (133, 'Chrysler', 'Fifth Ave', '3.18');
INSERT INTO car (id, make, model, price) VALUES (134, 'Mercedes-Benz', 'SLK-Class', '7.27');
INSERT INTO car (id, make, model, price) VALUES (135, 'Toyota', 'Avalon', '0.58');
INSERT INTO car (id, make, model, price) VALUES (136, 'Volvo', 'S80', '2.23');
INSERT INTO car (id, make, model, price) VALUES (137, 'Chevrolet', 'S10 Blazer', '7.70');
INSERT INTO car (id, make, model, price) VALUES (138, 'Mercedes-Benz', '400E', '0.97');
INSERT INTO car (id, make, model, price) VALUES (139, 'Oldsmobile', 'Cutlass Supreme', '9.00');
INSERT INTO car (id, make, model, price) VALUES (140, 'Mercury', 'Mariner', '8.16');
INSERT INTO car (id, make, model, price) VALUES (141, 'Land Rover', 'Discovery', '8.01');
INSERT INTO car (id, make, model, price) VALUES (142, 'Honda', 'CR-V', '9.08');
INSERT INTO car (id, make, model, price) VALUES (143, 'Hyundai', 'Azera', '6.85');
INSERT INTO car (id, make, model, price) VALUES (144, 'Chevrolet', 'Aveo', '2.55');
INSERT INTO car (id, make, model, price) VALUES (145, 'Nissan', '350Z', '7.76');
INSERT INTO car (id, make, model, price) VALUES (146, 'GMC', 'Canyon', '9.00');
INSERT INTO car (id, make, model, price) VALUES (147, 'GMC', 'Sierra 1500', '1.41');
INSERT INTO car (id, make, model, price) VALUES (148, 'Volvo', 'XC70', '4.13');
INSERT INTO car (id, make, model, price) VALUES (149, 'BMW', '325', '9.66');
INSERT INTO car (id, make, model, price) VALUES (150, 'Ford', 'Taurus', '2.29');
INSERT INTO car (id, make, model, price) VALUES (151, 'Jaguar', 'XJ Series', '9.00');
INSERT INTO car (id, make, model, price) VALUES (152, 'Dodge', 'Charger', '6.35');
INSERT INTO car (id, make, model, price) VALUES (153, 'Porsche', '911', '2.34');
INSERT INTO car (id, make, model, price) VALUES (154, 'Audi', 'A6', '4.11');
INSERT INTO car (id, make, model, price) VALUES (155, 'Honda', 'Odyssey', '9.01');
INSERT INTO car (id, make, model, price) VALUES (156, 'Maybach', '57', '4.47');
INSERT INTO car (id, make, model, price) VALUES (157, 'Volkswagen', 'Golf', '2.33');
INSERT INTO car (id, make, model, price) VALUES (158, 'Toyota', 'Solara', '2.50');
INSERT INTO car (id, make, model, price) VALUES (159, 'Saab', '9000', '1.53');
INSERT INTO car (id, make, model, price) VALUES (160, 'Suzuki', 'Forenza', '4.35');
INSERT INTO car (id, make, model, price) VALUES (161, 'Suzuki', 'Vitara', '7.27');
INSERT INTO car (id, make, model, price) VALUES (162, 'Land Rover', 'Range Rover', '7.35');
INSERT INTO car (id, make, model, price) VALUES (163, 'Audi', 'A6', '5.44');
INSERT INTO car (id, make, model, price) VALUES (164, 'Saturn', 'Astra', '8.26');
INSERT INTO car (id, make, model, price) VALUES (165, 'Toyota', 'Land Cruiser', '1.24');
INSERT INTO car (id, make, model, price) VALUES (166, 'Pontiac', 'Trans Sport', '5.46');
INSERT INTO car (id, make, model, price) VALUES (167, 'Chevrolet', 'Colorado', '3.29');
INSERT INTO car (id, make, model, price) VALUES (168, 'Audi', 'TT', '5.54');
INSERT INTO car (id, make, model, price) VALUES (169, 'Chevrolet', 'Cavalier', '1.92');
INSERT INTO car (id, make, model, price) VALUES (170, 'GMC', 'EV1', '7.94');
INSERT INTO car (id, make, model, price) VALUES (171, 'Chevrolet', 'Camaro', '0.30');
INSERT INTO car (id, make, model, price) VALUES (172, 'Ford', 'Ranger', '7.03');
INSERT INTO car (id, make, model, price) VALUES (173, 'Volvo', 'XC90', '7.05');
INSERT INTO car (id, make, model, price) VALUES (174, 'Ford', 'F250', '1.24');
INSERT INTO car (id, make, model, price) VALUES (175, 'Acura', 'Integra', '6.80');
INSERT INTO car (id, make, model, price) VALUES (176, 'Ford', 'Festiva', '0.25');
INSERT INTO car (id, make, model, price) VALUES (177, 'GMC', '1500 Club Coupe', '4.44');
INSERT INTO car (id, make, model, price) VALUES (178, 'Acura', 'SLX', '4.88');
INSERT INTO car (id, make, model, price) VALUES (179, 'Mercedes-Benz', 'S-Class', '5.86');
INSERT INTO car (id, make, model, price) VALUES (180, 'Pontiac', 'Grand Am', '0.81');
INSERT INTO car (id, make, model, price) VALUES (181, 'Lincoln', 'Continental', '5.96');
INSERT INTO car (id, make, model, price) VALUES (182, 'Toyota', 'Celica', '2.03');
INSERT INTO car (id, make, model, price) VALUES (183, 'Lexus', 'IS-F', '4.92');
INSERT INTO car (id, make, model, price) VALUES (184, 'Saturn', 'Ion', '6.70');
INSERT INTO car (id, make, model, price) VALUES (185, 'Subaru', 'Tribeca', '8.52');
INSERT INTO car (id, make, model, price) VALUES (186, 'Mazda', 'CX-9', '2.12');
INSERT INTO car (id, make, model, price) VALUES (187, 'Toyota', 'Land Cruiser', '3.65');
INSERT INTO car (id, make, model, price) VALUES (188, 'Audi', 'S4', '8.67');
INSERT INTO car (id, make, model, price) VALUES (189, 'Chrysler', 'PT Cruiser', '0.24');
INSERT INTO car (id, make, model, price) VALUES (190, 'Subaru', 'Legacy', '5.12');
INSERT INTO car (id, make, model, price) VALUES (191, 'Ford', 'Expedition', '4.86');
INSERT INTO car (id, make, model, price) VALUES (192, 'Buick', 'Regal', '9.14');
INSERT INTO car (id, make, model, price) VALUES (193, 'Dodge', 'Challenger', '7.55');
INSERT INTO car (id, make, model, price) VALUES (194, 'Alfa Romeo', '164', '6.63');
INSERT INTO car (id, make, model, price) VALUES (195, 'Isuzu', 'Hombre', '5.97');
INSERT INTO car (id, make, model, price) VALUES (196, 'Infiniti', 'Q', '4.99');
INSERT INTO car (id, make, model, price) VALUES (197, 'Toyota', 'Matrix', '3.49');
INSERT INTO car (id, make, model, price) VALUES (198, 'Acura', 'TSX', '5.64');
INSERT INTO car (id, make, model, price) VALUES (199, 'Toyota', 'Celica', '1.16');
INSERT INTO car (id, make, model, price) VALUES (200, 'Pontiac', 'LeMans', '2.98');
INSERT INTO car (id, make, model, price) VALUES (201, 'GMC', '1500 Club Coupe', '3.96');
INSERT INTO car (id, make, model, price) VALUES (202, 'GMC', 'Jimmy', '8.52');
INSERT INTO car (id, make, model, price) VALUES (203, 'Ford', 'Mustang', '9.25');
INSERT INTO car (id, make, model, price) VALUES (204, 'Saturn', 'VUE', '3.73');
INSERT INTO car (id, make, model, price) VALUES (205, 'Chrysler', 'New Yorker', '1.07');
INSERT INTO car (id, make, model, price) VALUES (206, 'Ford', 'Explorer', '8.05');
INSERT INTO car (id, make, model, price) VALUES (207, 'Hyundai', 'Santa Fe', '9.10');
INSERT INTO car (id, make, model, price) VALUES (208, 'Toyota', 'Yaris', '7.05');
INSERT INTO car (id, make, model, price) VALUES (209, 'Mazda', 'Tribute', '2.14');
INSERT INTO car (id, make, model, price) VALUES (210, 'Mercedes-Benz', 'E-Class', '5.53');
INSERT INTO car (id, make, model, price) VALUES (211, 'GMC', 'Vandura G3500', '8.05');
INSERT INTO car (id, make, model, price) VALUES (212, 'Alfa Romeo', '164', '4.50');
INSERT INTO car (id, make, model, price) VALUES (213, 'Honda', 'Pilot', '2.68');
INSERT INTO car (id, make, model, price) VALUES (214, 'Acura', 'NSX', '1.51');
INSERT INTO car (id, make, model, price) VALUES (215, 'Toyota', 'Corolla', '9.80');
INSERT INTO car (id, make, model, price) VALUES (216, 'Toyota', 'Matrix', '8.66');
INSERT INTO car (id, make, model, price) VALUES (217, 'MINI', 'Cooper Countryman', '7.12');
INSERT INTO car (id, make, model, price) VALUES (218, 'Nissan', 'Xterra', '8.31');
INSERT INTO car (id, make, model, price) VALUES (219, 'Pontiac', 'Bonneville', '5.00');
INSERT INTO car (id, make, model, price) VALUES (220, 'GMC', 'Sonoma', '3.82');
INSERT INTO car (id, make, model, price) VALUES (221, 'Honda', 'Civic', '4.07');
INSERT INTO car (id, make, model, price) VALUES (222, 'Toyota', 'RAV4', '1.46');
INSERT INTO car (id, make, model, price) VALUES (223, 'Ford', 'F-Series', '8.47');
INSERT INTO car (id, make, model, price) VALUES (224, 'Chevrolet', 'Silverado 1500', '5.01');
INSERT INTO car (id, make, model, price) VALUES (225, 'Nissan', 'Titan', '6.11');
INSERT INTO car (id, make, model, price) VALUES (226, 'Honda', 'Accord', '4.06');
INSERT INTO car (id, make, model, price) VALUES (227, 'Maserati', 'Spyder', '1.99');
INSERT INTO car (id, make, model, price) VALUES (228, 'Mitsubishi', 'Galant', '5.29');
INSERT INTO car (id, make, model, price) VALUES (229, 'Rolls-Royce', 'Phantom', '6.73');
INSERT INTO car (id, make, model, price) VALUES (230, 'Audi', 'S4', '6.43');
INSERT INTO car (id, make, model, price) VALUES (231, 'Chevrolet', 'Silverado 3500', '7.79');
INSERT INTO car (id, make, model, price) VALUES (232, 'Peugeot', '207', '5.65');
INSERT INTO car (id, make, model, price) VALUES (233, 'Mercury', 'Cougar', '0.66');
INSERT INTO car (id, make, model, price) VALUES (234, 'Lexus', 'LS', '8.02');
INSERT INTO car (id, make, model, price) VALUES (235, 'BMW', 'M5', '0.30');
INSERT INTO car (id, make, model, price) VALUES (236, 'Kia', 'Sportage', '1.06');
INSERT INTO car (id, make, model, price) VALUES (237, 'Volkswagen', 'Rabbit', '3.36');
INSERT INTO car (id, make, model, price) VALUES (238, 'Lexus', 'IS-F', '0.77');
INSERT INTO car (id, make, model, price) VALUES (239, 'Infiniti', 'G', '2.11');
INSERT INTO car (id, make, model, price) VALUES (240, 'Dodge', 'Grand Caravan', '1.08');
INSERT INTO car (id, make, model, price) VALUES (241, 'Pontiac', 'Grand Prix', '5.02');
INSERT INTO car (id, make, model, price) VALUES (242, 'Chevrolet', 'Express 3500', '8.69');
INSERT INTO car (id, make, model, price) VALUES (243, 'Chrysler', 'Prowler', '0.59');
INSERT INTO car (id, make, model, price) VALUES (244, 'Toyota', 'Camry', '6.10');
INSERT INTO car (id, make, model, price) VALUES (245, 'Acura', 'TSX', '8.91');
INSERT INTO car (id, make, model, price) VALUES (246, 'Toyota', 'Corolla', '6.14');
INSERT INTO car (id, make, model, price) VALUES (247, 'Lincoln', 'Town Car', '2.05');
INSERT INTO car (id, make, model, price) VALUES (248, 'Lexus', 'GX', '8.05');
INSERT INTO car (id, make, model, price) VALUES (249, 'Ford', 'Mustang', '7.07');
INSERT INTO car (id, make, model, price) VALUES (250, 'Mazda', 'MPV', '0.98');
INSERT INTO car (id, make, model, price) VALUES (251, 'Mercedes-Benz', 'W201', '2.91');
INSERT INTO car (id, make, model, price) VALUES (252, 'Aston Martin', 'DB9', '1.83');
INSERT INTO car (id, make, model, price) VALUES (253, 'Aston Martin', 'DB9', '0.02');
INSERT INTO car (id, make, model, price) VALUES (254, 'Nissan', 'Altima', '4.27');
INSERT INTO car (id, make, model, price) VALUES (255, 'Ford', 'Econoline E150', '2.73');
INSERT INTO car (id, make, model, price) VALUES (256, 'Toyota', 'Venza', '1.93');
INSERT INTO car (id, make, model, price) VALUES (257, 'Plymouth', 'Colt', '3.01');
INSERT INTO car (id, make, model, price) VALUES (258, 'Pontiac', 'Trans Sport', '8.48');
INSERT INTO car (id, make, model, price) VALUES (259, 'Mitsubishi', 'Challenger', '3.73');
INSERT INTO car (id, make, model, price) VALUES (260, 'Toyota', 'Solara', '8.27');
INSERT INTO car (id, make, model, price) VALUES (261, 'Nissan', '240SX', '6.49');
INSERT INTO car (id, make, model, price) VALUES (262, 'Ford', 'Escort', '9.79');
INSERT INTO car (id, make, model, price) VALUES (263, 'Toyota', 'Celica', '3.35');
INSERT INTO car (id, make, model, price) VALUES (264, 'Mazda', 'Familia', '5.16');
INSERT INTO car (id, make, model, price) VALUES (265, 'Nissan', 'Titan', '1.32');
INSERT INTO car (id, make, model, price) VALUES (266, 'Acura', 'Integra', '3.59');
INSERT INTO car (id, make, model, price) VALUES (267, 'BMW', '650', '1.35');
INSERT INTO car (id, make, model, price) VALUES (268, 'Volvo', 'C30', '7.83');
INSERT INTO car (id, make, model, price) VALUES (269, 'Mazda', 'CX-7', '6.90');
INSERT INTO car (id, make, model, price) VALUES (270, 'Mercury', 'Mountaineer', '7.25');
INSERT INTO car (id, make, model, price) VALUES (271, 'Mitsubishi', 'Mirage', '5.31');
INSERT INTO car (id, make, model, price) VALUES (272, 'Pontiac', 'Bonneville', '1.88');
INSERT INTO car (id, make, model, price) VALUES (273, 'Chevrolet', 'Silverado 1500', '9.08');
INSERT INTO car (id, make, model, price) VALUES (274, 'Mazda', '929', '1.33');
INSERT INTO car (id, make, model, price) VALUES (275, 'Pontiac', 'Trans Sport', '2.39');
INSERT INTO car (id, make, model, price) VALUES (276, 'Suzuki', 'Equator', '3.09');
INSERT INTO car (id, make, model, price) VALUES (277, 'Kia', 'Sportage', '0.31');
INSERT INTO car (id, make, model, price) VALUES (278, 'Pontiac', 'Grand Prix', '9.05');
INSERT INTO car (id, make, model, price) VALUES (279, 'Ford', 'Ranger', '3.85');
INSERT INTO car (id, make, model, price) VALUES (280, 'Honda', 'Pilot', '6.37');
INSERT INTO car (id, make, model, price) VALUES (281, 'Volkswagen', 'New Beetle', '4.55');
INSERT INTO car (id, make, model, price) VALUES (282, 'Ford', 'Ranger', '7.10');
INSERT INTO car (id, make, model, price) VALUES (283, 'Chevrolet', 'Suburban 1500', '8.03');
INSERT INTO car (id, make, model, price) VALUES (284, 'Oldsmobile', 'Bravada', '6.39');
INSERT INTO car (id, make, model, price) VALUES (285, 'Chevrolet', 'Express 3500', '0.52');
INSERT INTO car (id, make, model, price) VALUES (286, 'Subaru', 'Loyale', '4.87');
INSERT INTO car (id, make, model, price) VALUES (287, 'Volvo', 'S80', '4.51');
INSERT INTO car (id, make, model, price) VALUES (288, 'Chevrolet', 'Prizm', '3.95');
INSERT INTO car (id, make, model, price) VALUES (289, 'Mercedes-Benz', 'M-Class', '2.06');
INSERT INTO car (id, make, model, price) VALUES (290, 'Isuzu', 'VehiCROSS', '3.53');
INSERT INTO car (id, make, model, price) VALUES (291, 'Lexus', 'ES', '8.09');
INSERT INTO car (id, make, model, price) VALUES (292, 'Saab', '9-5', '3.89');
INSERT INTO car (id, make, model, price) VALUES (293, 'Land Rover', 'LR4', '2.13');
INSERT INTO car (id, make, model, price) VALUES (294, 'Suzuki', 'Aerio', '1.04');
INSERT INTO car (id, make, model, price) VALUES (295, 'Mazda', 'Tribute', '6.65');
INSERT INTO car (id, make, model, price) VALUES (296, 'Chevrolet', 'Silverado 1500', '1.75');
INSERT INTO car (id, make, model, price) VALUES (297, 'Toyota', 'FJ Cruiser', '6.33');
INSERT INTO car (id, make, model, price) VALUES (298, 'Chevrolet', 'S10', '3.04');
INSERT INTO car (id, make, model, price) VALUES (299, 'Mazda', 'CX-9', '6.60');
INSERT INTO car (id, make, model, price) VALUES (300, 'Saturn', 'VUE', '2.04');
INSERT INTO car (id, make, model, price) VALUES (301, 'Ford', 'E-Series', '6.74');
INSERT INTO car (id, make, model, price) VALUES (302, 'Subaru', 'Baja', '3.89');
INSERT INTO car (id, make, model, price) VALUES (303, 'Ford', 'Mustang', '10.00');
INSERT INTO car (id, make, model, price) VALUES (304, 'Mercedes-Benz', 'E-Class', '0.80');
INSERT INTO car (id, make, model, price) VALUES (305, 'Ford', 'Escort', '7.63');
INSERT INTO car (id, make, model, price) VALUES (306, 'Mercedes-Benz', 'M-Class', '2.66');
INSERT INTO car (id, make, model, price) VALUES (307, 'Kia', 'Sportage', '9.64');
INSERT INTO car (id, make, model, price) VALUES (308, 'Nissan', 'Xterra', '8.45');
INSERT INTO car (id, make, model, price) VALUES (309, 'Volkswagen', 'Touareg 2', '3.57');
INSERT INTO car (id, make, model, price) VALUES (310, 'Nissan', 'Cube', '7.29');
INSERT INTO car (id, make, model, price) VALUES (311, 'Toyota', 'TundraMax', '4.89');
INSERT INTO car (id, make, model, price) VALUES (312, 'Buick', 'Park Avenue', '3.64');
INSERT INTO car (id, make, model, price) VALUES (313, 'Chevrolet', 'G-Series G30', '5.70');
INSERT INTO car (id, make, model, price) VALUES (314, 'Acura', 'RL', '8.55');
INSERT INTO car (id, make, model, price) VALUES (315, 'Mitsubishi', 'Pajero', '9.38');
INSERT INTO car (id, make, model, price) VALUES (316, 'Alfa Romeo', '164', '7.33');
INSERT INTO car (id, make, model, price) VALUES (317, 'Dodge', 'Ram Van 3500', '9.33');
INSERT INTO car (id, make, model, price) VALUES (318, 'BMW', 'X5', '8.03');
INSERT INTO car (id, make, model, price) VALUES (319, 'Mitsubishi', 'Mirage', '5.34');
INSERT INTO car (id, make, model, price) VALUES (320, 'Suzuki', 'Equator', '0.86');
INSERT INTO car (id, make, model, price) VALUES (321, 'Chevrolet', 'Impala', '1.65');
INSERT INTO car (id, make, model, price) VALUES (322, 'Mitsubishi', 'Montero', '0.86');
INSERT INTO car (id, make, model, price) VALUES (323, 'Mitsubishi', 'Eclipse', '7.62');
INSERT INTO car (id, make, model, price) VALUES (324, 'Hyundai', 'Elantra', '1.43');
INSERT INTO car (id, make, model, price) VALUES (325, 'Lexus', 'ES', '3.45');
INSERT INTO car (id, make, model, price) VALUES (326, 'Mazda', 'MPV', '2.26');
INSERT INTO car (id, make, model, price) VALUES (327, 'Volvo', 'V70', '1.74');
INSERT INTO car (id, make, model, price) VALUES (328, 'Ford', 'Tempo', '3.95');
INSERT INTO car (id, make, model, price) VALUES (329, 'Toyota', 'MR2', '9.79');
INSERT INTO car (id, make, model, price) VALUES (330, 'Subaru', 'Brat', '4.84');
INSERT INTO car (id, make, model, price) VALUES (331, 'Pontiac', 'Grand Prix', '8.66');
INSERT INTO car (id, make, model, price) VALUES (332, 'Volkswagen', 'Golf', '1.42');
INSERT INTO car (id, make, model, price) VALUES (333, 'Mazda', 'MX-5', '0.75');
INSERT INTO car (id, make, model, price) VALUES (334, 'Buick', 'Skylark', '5.02');
INSERT INTO car (id, make, model, price) VALUES (335, 'Mercedes-Benz', 'S-Class', '3.25');
INSERT INTO car (id, make, model, price) VALUES (336, 'Chevrolet', 'Express 3500', '0.74');
INSERT INTO car (id, make, model, price) VALUES (337, 'Volkswagen', 'Golf', '0.92');
INSERT INTO car (id, make, model, price) VALUES (338, 'Audi', 'V8', '8.97');
INSERT INTO car (id, make, model, price) VALUES (339, 'Lexus', 'IS-F', '5.59');
INSERT INTO car (id, make, model, price) VALUES (340, 'GMC', 'Envoy XL', '6.59');
INSERT INTO car (id, make, model, price) VALUES (341, 'BMW', '5 Series', '7.27');
INSERT INTO car (id, make, model, price) VALUES (342, 'Pontiac', 'Grand Am', '4.87');
INSERT INTO car (id, make, model, price) VALUES (343, 'Nissan', 'Sentra', '7.33');
INSERT INTO car (id, make, model, price) VALUES (344, 'Ford', 'Freestar', '6.78');
INSERT INTO car (id, make, model, price) VALUES (345, 'Buick', 'Regal', '8.74');
INSERT INTO car (id, make, model, price) VALUES (346, 'Toyota', 'MR2', '0.05');
INSERT INTO car (id, make, model, price) VALUES (347, 'Toyota', 'RAV4', '3.34');
INSERT INTO car (id, make, model, price) VALUES (348, 'Citroën', 'CX', '2.59');
INSERT INTO car (id, make, model, price) VALUES (349, 'Pontiac', 'Grand Prix', '3.01');
INSERT INTO car (id, make, model, price) VALUES (350, 'Dodge', 'Grand Caravan', '8.35');
INSERT INTO car (id, make, model, price) VALUES (351, 'Suzuki', 'Equator', '5.33');
INSERT INTO car (id, make, model, price) VALUES (352, 'Mitsubishi', 'Outlander', '7.19');
INSERT INTO car (id, make, model, price) VALUES (353, 'Ford', 'F-Series', '2.31');
INSERT INTO car (id, make, model, price) VALUES (354, 'GMC', 'Savana 2500', '7.12');
INSERT INTO car (id, make, model, price) VALUES (355, 'Dodge', 'Ram 3500', '6.55');
INSERT INTO car (id, make, model, price) VALUES (356, 'GMC', 'Rally Wagon 2500', '4.17');
INSERT INTO car (id, make, model, price) VALUES (357, 'Chevrolet', 'Uplander', '3.17');
INSERT INTO car (id, make, model, price) VALUES (358, 'Ford', 'F-Series Super Duty', '4.05');
INSERT INTO car (id, make, model, price) VALUES (359, 'Chrysler', 'Crossfire', '5.82');
INSERT INTO car (id, make, model, price) VALUES (360, 'Suzuki', 'Vitara', '9.47');
INSERT INTO car (id, make, model, price) VALUES (361, 'Lexus', 'ES', '3.90');
INSERT INTO car (id, make, model, price) VALUES (362, 'GMC', 'Yukon XL 2500', '4.91');
INSERT INTO car (id, make, model, price) VALUES (363, 'Land Rover', 'Range Rover', '1.41');
INSERT INTO car (id, make, model, price) VALUES (364, 'Nissan', 'Leaf', '0.97');
INSERT INTO car (id, make, model, price) VALUES (365, 'Chevrolet', 'Silverado 1500', '4.59');
INSERT INTO car (id, make, model, price) VALUES (366, 'Isuzu', 'Axiom', '1.23');
INSERT INTO car (id, make, model, price) VALUES (367, 'Dodge', 'Dakota Club', '1.31');
INSERT INTO car (id, make, model, price) VALUES (368, 'Saab', '9-5', '9.58');
INSERT INTO car (id, make, model, price) VALUES (369, 'Dodge', 'Grand Caravan', '5.63');
INSERT INTO car (id, make, model, price) VALUES (370, 'Ford', 'Crown Victoria', '4.23');
INSERT INTO car (id, make, model, price) VALUES (371, 'Jeep', 'Liberty', '0.83');
INSERT INTO car (id, make, model, price) VALUES (372, 'Lincoln', 'Mark VIII', '1.71');
INSERT INTO car (id, make, model, price) VALUES (373, 'BMW', 'M5', '0.64');
INSERT INTO car (id, make, model, price) VALUES (374, 'Jaguar', 'XJ', '1.67');
INSERT INTO car (id, make, model, price) VALUES (375, 'Jeep', 'Grand Cherokee', '4.19');
INSERT INTO car (id, make, model, price) VALUES (376, 'Chevrolet', 'TrailBlazer', '5.92');
INSERT INTO car (id, make, model, price) VALUES (377, 'Toyota', 'T100', '4.83');
INSERT INTO car (id, make, model, price) VALUES (378, 'GMC', 'Safari', '1.21');
INSERT INTO car (id, make, model, price) VALUES (379, 'Ford', 'Ranger', '5.07');
INSERT INTO car (id, make, model, price) VALUES (380, 'Toyota', 'Tercel', '3.07');
INSERT INTO car (id, make, model, price) VALUES (381, 'Ford', 'Focus', '2.40');
INSERT INTO car (id, make, model, price) VALUES (382, 'Dodge', 'Ram 2500', '8.16');
INSERT INTO car (id, make, model, price) VALUES (383, 'Dodge', 'Neon', '3.56');
INSERT INTO car (id, make, model, price) VALUES (384, 'Ford', 'Thunderbird', '7.15');
INSERT INTO car (id, make, model, price) VALUES (385, 'Dodge', 'Neon', '6.56');
INSERT INTO car (id, make, model, price) VALUES (386, 'Chevrolet', 'Lumina', '7.09');
INSERT INTO car (id, make, model, price) VALUES (387, 'Honda', 'Accord', '6.98');
INSERT INTO car (id, make, model, price) VALUES (388, 'GMC', 'Canyon', '5.69');
INSERT INTO car (id, make, model, price) VALUES (389, 'Pontiac', 'Bonneville', '0.31');
INSERT INTO car (id, make, model, price) VALUES (390, 'Hyundai', 'Sonata', '0.75');
INSERT INTO car (id, make, model, price) VALUES (391, 'Lincoln', 'Continental Mark VII', '8.68');
INSERT INTO car (id, make, model, price) VALUES (392, 'Dodge', 'Charger', '7.38');
INSERT INTO car (id, make, model, price) VALUES (393, 'Plymouth', 'Grand Voyager', '5.47');
INSERT INTO car (id, make, model, price) VALUES (394, 'Mercedes-Benz', 'CL-Class', '2.46');
INSERT INTO car (id, make, model, price) VALUES (395, 'Mercury', 'Tracer', '8.40');
INSERT INTO car (id, make, model, price) VALUES (396, 'Pontiac', 'G5', '10.00');
INSERT INTO car (id, make, model, price) VALUES (397, 'GMC', 'Savana 3500', '9.49');
INSERT INTO car (id, make, model, price) VALUES (398, 'Dodge', 'Grand Caravan', '6.13');
INSERT INTO car (id, make, model, price) VALUES (399, 'Ford', 'E-Series', '5.28');
INSERT INTO car (id, make, model, price) VALUES (400, 'Audi', '4000s', '3.88');
INSERT INTO car (id, make, model, price) VALUES (401, 'Pontiac', 'Vibe', '6.33');
INSERT INTO car (id, make, model, price) VALUES (402, 'Honda', 'Prelude', '3.70');
INSERT INTO car (id, make, model, price) VALUES (403, 'Mazda', 'Mazda3', '8.22');
INSERT INTO car (id, make, model, price) VALUES (404, 'Nissan', 'Pathfinder', '8.45');
INSERT INTO car (id, make, model, price) VALUES (405, 'Ford', 'Escort', '0.67');
INSERT INTO car (id, make, model, price) VALUES (406, 'Buick', 'Century', '3.18');
INSERT INTO car (id, make, model, price) VALUES (407, 'Ford', 'Escort', '4.84');
INSERT INTO car (id, make, model, price) VALUES (408, 'Mitsubishi', 'RVR', '5.38');
INSERT INTO car (id, make, model, price) VALUES (409, 'Audi', '100', '5.20');
INSERT INTO car (id, make, model, price) VALUES (410, 'Mitsubishi', 'Montero', '5.15');
INSERT INTO car (id, make, model, price) VALUES (411, 'Suzuki', 'Grand Vitara', '2.71');
INSERT INTO car (id, make, model, price) VALUES (412, 'Mercedes-Benz', 'SL-Class', '4.35');
INSERT INTO car (id, make, model, price) VALUES (413, 'Ford', 'Mustang', '4.32');
INSERT INTO car (id, make, model, price) VALUES (414, 'Lotus', 'Esprit', '8.61');
INSERT INTO car (id, make, model, price) VALUES (415, 'Mercedes-Benz', 'M-Class', '8.57');
INSERT INTO car (id, make, model, price) VALUES (416, 'Pontiac', 'Tempest', '0.63');
INSERT INTO car (id, make, model, price) VALUES (417, 'Lexus', 'SC', '4.59');
INSERT INTO car (id, make, model, price) VALUES (418, 'Dodge', 'Grand Caravan', '6.67');
INSERT INTO car (id, make, model, price) VALUES (419, 'Chrysler', 'New Yorker', '1.99');
INSERT INTO car (id, make, model, price) VALUES (420, 'Mercury', 'Capri', '0.59');
INSERT INTO car (id, make, model, price) VALUES (421, 'Kia', 'Sedona', '2.47');
INSERT INTO car (id, make, model, price) VALUES (422, 'Chevrolet', 'Blazer', '5.70');
INSERT INTO car (id, make, model, price) VALUES (423, 'Pontiac', 'LeMans', '7.27');
INSERT INTO car (id, make, model, price) VALUES (424, 'Dodge', 'Ram Van 2500', '4.45');
INSERT INTO car (id, make, model, price) VALUES (425, 'Mitsubishi', 'Eclipse', '3.29');
INSERT INTO car (id, make, model, price) VALUES (426, 'Mercedes-Benz', 'C-Class', '3.01');
INSERT INTO car (id, make, model, price) VALUES (427, 'Ford', 'F450', '2.48');
INSERT INTO car (id, make, model, price) VALUES (428, 'Audi', 'A8', '7.04');
INSERT INTO car (id, make, model, price) VALUES (429, 'Bentley', 'Azure', '5.37');
INSERT INTO car (id, make, model, price) VALUES (430, 'Buick', 'Century', '7.69');
INSERT INTO car (id, make, model, price) VALUES (431, 'Buick', 'Electra', '2.50');
INSERT INTO car (id, make, model, price) VALUES (432, 'Acura', 'TL', '2.32');
INSERT INTO car (id, make, model, price) VALUES (433, 'Cadillac', 'Catera', '3.02');
INSERT INTO car (id, make, model, price) VALUES (434, 'Chevrolet', 'Suburban 1500', '6.47');
INSERT INTO car (id, make, model, price) VALUES (435, 'GMC', 'Sonoma', '1.00');
INSERT INTO car (id, make, model, price) VALUES (436, 'Mitsubishi', 'Outlander', '3.49');
INSERT INTO car (id, make, model, price) VALUES (437, 'Mercury', 'Mystique', '4.77');
INSERT INTO car (id, make, model, price) VALUES (438, 'Aston Martin', 'V8 Vantage S', '6.62');
INSERT INTO car (id, make, model, price) VALUES (439, 'Buick', 'Terraza', '6.10');
INSERT INTO car (id, make, model, price) VALUES (440, 'GMC', 'Yukon XL 2500', '5.19');
INSERT INTO car (id, make, model, price) VALUES (441, 'Jaguar', 'S-Type', '7.31');
INSERT INTO car (id, make, model, price) VALUES (442, 'Mitsubishi', 'Challenger', '9.88');
INSERT INTO car (id, make, model, price) VALUES (443, 'Toyota', 'Corolla', '9.61');
INSERT INTO car (id, make, model, price) VALUES (444, 'Buick', 'Riviera', '7.97');
INSERT INTO car (id, make, model, price) VALUES (445, 'Cadillac', 'CTS', '8.66');
INSERT INTO car (id, make, model, price) VALUES (446, 'Lexus', 'GX', '1.16');
INSERT INTO car (id, make, model, price) VALUES (447, 'Mazda', 'MPV', '8.24');
INSERT INTO car (id, make, model, price) VALUES (448, 'Toyota', 'Camry', '0.86');
INSERT INTO car (id, make, model, price) VALUES (449, 'BMW', '5 Series', '5.49');
INSERT INTO car (id, make, model, price) VALUES (450, 'Mercury', 'Topaz', '8.80');
INSERT INTO car (id, make, model, price) VALUES (451, 'Mercury', 'Grand Marquis', '1.34');
INSERT INTO car (id, make, model, price) VALUES (452, 'Chevrolet', 'Impala', '2.54');
INSERT INTO car (id, make, model, price) VALUES (453, 'Kia', 'Sephia', '4.94');
INSERT INTO car (id, make, model, price) VALUES (454, 'Lexus', 'GS', '5.92');
INSERT INTO car (id, make, model, price) VALUES (455, 'Lincoln', 'Continental', '2.03');
INSERT INTO car (id, make, model, price) VALUES (456, 'Volkswagen', 'Jetta', '8.21');
INSERT INTO car (id, make, model, price) VALUES (457, 'Kia', 'Sportage', '5.65');
INSERT INTO car (id, make, model, price) VALUES (458, 'Chevrolet', 'Prizm', '8.53');
INSERT INTO car (id, make, model, price) VALUES (459, 'GMC', '3500', '0.88');
INSERT INTO car (id, make, model, price) VALUES (460, 'Kia', 'Sportage', '5.23');
INSERT INTO car (id, make, model, price) VALUES (461, 'Mercury', 'Grand Marquis', '4.63');
INSERT INTO car (id, make, model, price) VALUES (462, 'Mercedes-Benz', 'SLK-Class', '0.72');
INSERT INTO car (id, make, model, price) VALUES (463, 'Nissan', 'Xterra', '5.96');
INSERT INTO car (id, make, model, price) VALUES (464, 'Infiniti', 'QX', '2.73');
INSERT INTO car (id, make, model, price) VALUES (465, 'Volkswagen', 'Passat', '4.63');
INSERT INTO car (id, make, model, price) VALUES (466, 'Oldsmobile', 'Cutlass Supreme', '3.81');
INSERT INTO car (id, make, model, price) VALUES (467, 'Hyundai', 'XG350', '7.73');
INSERT INTO car (id, make, model, price) VALUES (468, 'Land Rover', 'Range Rover Sport', '7.66');
INSERT INTO car (id, make, model, price) VALUES (469, 'Saturn', 'Sky', '0.22');
INSERT INTO car (id, make, model, price) VALUES (470, 'Dodge', 'Ram 1500', '6.35');
INSERT INTO car (id, make, model, price) VALUES (471, 'Honda', 'Accord', '0.74');
INSERT INTO car (id, make, model, price) VALUES (472, 'Maybach', '57S', '5.05');
INSERT INTO car (id, make, model, price) VALUES (473, 'Chevrolet', 'Malibu', '5.64');
INSERT INTO car (id, make, model, price) VALUES (474, 'Ford', 'F350', '7.99');
INSERT INTO car (id, make, model, price) VALUES (475, 'Ford', 'E150', '4.78');
INSERT INTO car (id, make, model, price) VALUES (476, 'Kia', 'Sephia', '9.50');
INSERT INTO car (id, make, model, price) VALUES (477, 'Chevrolet', 'Suburban 2500', '4.83');
INSERT INTO car (id, make, model, price) VALUES (478, 'Toyota', 'Corolla', '0.90');
INSERT INTO car (id, make, model, price) VALUES (479, 'Honda', 'CR-Z', '3.01');
INSERT INTO car (id, make, model, price) VALUES (480, 'Ford', 'Tempo', '2.99');
INSERT INTO car (id, make, model, price) VALUES (481, 'Hyundai', 'Tucson', '4.49');
INSERT INTO car (id, make, model, price) VALUES (482, 'Pontiac', 'Trans Sport', '5.97');
INSERT INTO car (id, make, model, price) VALUES (483, 'Chevrolet', 'Cavalier', '0.46');
INSERT INTO car (id, make, model, price) VALUES (484, 'Austin', 'Mini', '4.57');
INSERT INTO car (id, make, model, price) VALUES (485, 'Hyundai', 'Veloster', '9.60');
INSERT INTO car (id, make, model, price) VALUES (486, 'Mazda', 'B-Series', '3.27');
INSERT INTO car (id, make, model, price) VALUES (487, 'Saab', '9-3', '4.41');
INSERT INTO car (id, make, model, price) VALUES (488, 'Chevrolet', 'Venture', '2.99');
INSERT INTO car (id, make, model, price) VALUES (489, 'Chrysler', 'Voyager', '7.33');
INSERT INTO car (id, make, model, price) VALUES (490, 'GMC', 'Sierra 2500', '7.60');
INSERT INTO car (id, make, model, price) VALUES (491, 'Mercury', 'Grand Marquis', '0.64');
INSERT INTO car (id, make, model, price) VALUES (492, 'Suzuki', 'Forenza', '0.38');
INSERT INTO car (id, make, model, price) VALUES (493, 'Porsche', 'Carrera GT', '6.00');
INSERT INTO car (id, make, model, price) VALUES (494, 'Lincoln', 'MKZ', '7.42');
INSERT INTO car (id, make, model, price) VALUES (495, 'Ford', 'Focus', '0.89');
INSERT INTO car (id, make, model, price) VALUES (496, 'Lexus', 'GS', '2.48');
INSERT INTO car (id, make, model, price) VALUES (497, 'Chevrolet', '1500', '4.97');
INSERT INTO car (id, make, model, price) VALUES (498, 'Toyota', 'Sienna', '4.10');
INSERT INTO car (id, make, model, price) VALUES (499, 'Mazda', 'Protege', '9.81');
INSERT INTO car (id, make, model, price) VALUES (500, 'BMW', '7 Series', '3.41');
INSERT INTO car (id, make, model, price) VALUES (501, 'Pontiac', 'GTO', '4.40');
INSERT INTO car (id, make, model, price) VALUES (502, 'Dodge', 'Dakota Club', '5.60');
INSERT INTO car (id, make, model, price) VALUES (503, 'Pontiac', 'Bonneville', '8.98');
INSERT INTO car (id, make, model, price) VALUES (504, 'Infiniti', 'QX', '6.88');
INSERT INTO car (id, make, model, price) VALUES (505, 'Chevrolet', 'Tahoe', '0.70');
INSERT INTO car (id, make, model, price) VALUES (506, 'Jaguar', 'XJ Series', '6.32');
INSERT INTO car (id, make, model, price) VALUES (507, 'Dodge', 'Spirit', '5.19');
INSERT INTO car (id, make, model, price) VALUES (508, 'Chevrolet', 'Impala', '6.78');
INSERT INTO car (id, make, model, price) VALUES (509, 'Ford', 'Tempo', '1.33');
INSERT INTO car (id, make, model, price) VALUES (510, 'Isuzu', 'Ascender', '4.61');
INSERT INTO car (id, make, model, price) VALUES (511, 'GMC', 'Vandura 1500', '2.52');
INSERT INTO car (id, make, model, price) VALUES (512, 'Lexus', 'ES', '9.88');
INSERT INTO car (id, make, model, price) VALUES (513, 'Chevrolet', '3500', '4.88');
INSERT INTO car (id, make, model, price) VALUES (514, 'Lexus', 'RX Hybrid', '9.97');
INSERT INTO car (id, make, model, price) VALUES (515, 'Scion', 'xB', '4.76');
INSERT INTO car (id, make, model, price) VALUES (516, 'Mitsubishi', 'Lancer', '9.87');
INSERT INTO car (id, make, model, price) VALUES (517, 'Dodge', 'Durango', '6.88');
INSERT INTO car (id, make, model, price) VALUES (518, 'Chevrolet', 'Camaro', '8.03');
INSERT INTO car (id, make, model, price) VALUES (519, 'Chevrolet', 'Silverado 1500', '8.58');
INSERT INTO car (id, make, model, price) VALUES (520, 'BMW', '3 Series', '2.19');
INSERT INTO car (id, make, model, price) VALUES (521, 'Volkswagen', 'GTI', '2.65');
INSERT INTO car (id, make, model, price) VALUES (522, 'Mazda', 'MX-5', '9.20');
INSERT INTO car (id, make, model, price) VALUES (523, 'Lexus', 'GS', '6.39');
INSERT INTO car (id, make, model, price) VALUES (524, 'Nissan', 'Maxima', '8.19');
INSERT INTO car (id, make, model, price) VALUES (525, 'Pontiac', 'Gemini', '0.90');
INSERT INTO car (id, make, model, price) VALUES (526, 'Porsche', '911', '1.63');
INSERT INTO car (id, make, model, price) VALUES (527, 'Suzuki', 'Grand Vitara', '5.47');
INSERT INTO car (id, make, model, price) VALUES (528, 'Chevrolet', 'Tracker', '2.54');
INSERT INTO car (id, make, model, price) VALUES (529, 'Mazda', 'CX-7', '0.21');
INSERT INTO car (id, make, model, price) VALUES (530, 'Jensen', 'Interceptor', '8.02');
INSERT INTO car (id, make, model, price) VALUES (531, 'Cadillac', 'CTS', '2.40');
INSERT INTO car (id, make, model, price) VALUES (532, 'Toyota', 'Prius', '2.87');
INSERT INTO car (id, make, model, price) VALUES (533, 'Chevrolet', 'Silverado', '8.46');
INSERT INTO car (id, make, model, price) VALUES (534, 'Audi', '100', '1.25');
INSERT INTO car (id, make, model, price) VALUES (535, 'Mazda', 'MPV', '4.06');
INSERT INTO car (id, make, model, price) VALUES (536, 'MINI', 'Cooper', '4.46');
INSERT INTO car (id, make, model, price) VALUES (537, 'Hummer', 'H1', '9.34');
INSERT INTO car (id, make, model, price) VALUES (538, 'Chevrolet', 'S10', '6.42');
INSERT INTO car (id, make, model, price) VALUES (539, 'Chevrolet', 'Silverado 1500', '5.06');
INSERT INTO car (id, make, model, price) VALUES (540, 'Chrysler', 'Sebring', '5.08');
INSERT INTO car (id, make, model, price) VALUES (541, 'Suzuki', 'SX4', '7.40');
INSERT INTO car (id, make, model, price) VALUES (542, 'Daewoo', 'Leganza', '1.08');
INSERT INTO car (id, make, model, price) VALUES (543, 'Chevrolet', 'Blazer', '7.58');
INSERT INTO car (id, make, model, price) VALUES (544, 'Chevrolet', 'Express 2500', '6.53');
INSERT INTO car (id, make, model, price) VALUES (545, 'Pontiac', 'LeMans', '3.22');
INSERT INTO car (id, make, model, price) VALUES (546, 'Fiat', '500', '3.91');
INSERT INTO car (id, make, model, price) VALUES (547, 'Infiniti', 'QX56', '1.96');
INSERT INTO car (id, make, model, price) VALUES (548, 'Toyota', 'Tacoma Xtra', '7.96');
INSERT INTO car (id, make, model, price) VALUES (549, 'Mercedes-Benz', '500SEL', '9.30');
INSERT INTO car (id, make, model, price) VALUES (550, 'Chevrolet', 'Suburban 1500', '3.59');
INSERT INTO car (id, make, model, price) VALUES (551, 'Mercedes-Benz', 'GLK-Class', '1.39');
INSERT INTO car (id, make, model, price) VALUES (552, 'Audi', 'A8', '0.45');
INSERT INTO car (id, make, model, price) VALUES (553, 'Pontiac', 'Safari', '9.38');
INSERT INTO car (id, make, model, price) VALUES (554, 'Cadillac', 'Escalade EXT', '0.55');
INSERT INTO car (id, make, model, price) VALUES (555, 'Volkswagen', 'Jetta', '6.80');
INSERT INTO car (id, make, model, price) VALUES (556, 'Buick', 'Coachbuilder', '4.05');
INSERT INTO car (id, make, model, price) VALUES (557, 'Ram', '1500', '8.81');
INSERT INTO car (id, make, model, price) VALUES (558, 'BMW', 'X3', '9.20');
INSERT INTO car (id, make, model, price) VALUES (559, 'Chevrolet', 'Lumina', '9.73');
INSERT INTO car (id, make, model, price) VALUES (560, 'Chevrolet', 'Traverse', '3.77');
INSERT INTO car (id, make, model, price) VALUES (561, 'Lexus', 'LX', '0.71');
INSERT INTO car (id, make, model, price) VALUES (562, 'Bentley', 'Continental Super', '5.39');
INSERT INTO car (id, make, model, price) VALUES (563, 'BMW', 'M5', '9.75');
INSERT INTO car (id, make, model, price) VALUES (564, 'Porsche', '928', '2.92');
INSERT INTO car (id, make, model, price) VALUES (565, 'Mercedes-Benz', 'S-Class', '0.03');
INSERT INTO car (id, make, model, price) VALUES (566, 'BMW', 'X3', '3.14');
INSERT INTO car (id, make, model, price) VALUES (567, 'Chevrolet', 'Caprice', '7.79');
INSERT INTO car (id, make, model, price) VALUES (568, 'Mercedes-Benz', '500E', '5.80');
INSERT INTO car (id, make, model, price) VALUES (569, 'Toyota', 'Corolla', '9.71');
INSERT INTO car (id, make, model, price) VALUES (570, 'Kia', 'Sedona', '2.46');
INSERT INTO car (id, make, model, price) VALUES (571, 'Pontiac', 'Tempest', '0.85');
INSERT INTO car (id, make, model, price) VALUES (572, 'Mazda', '929', '2.33');
INSERT INTO car (id, make, model, price) VALUES (573, 'Saturn', 'Outlook', '8.22');
INSERT INTO car (id, make, model, price) VALUES (574, 'Mercury', 'Villager', '8.82');
INSERT INTO car (id, make, model, price) VALUES (575, 'Dodge', 'Caravan', '3.57');
INSERT INTO car (id, make, model, price) VALUES (576, 'Cadillac', 'SRX', '7.27');
INSERT INTO car (id, make, model, price) VALUES (577, 'Lotus', 'Evora', '6.15');
INSERT INTO car (id, make, model, price) VALUES (578, 'Dodge', 'Dakota Club', '0.71');
INSERT INTO car (id, make, model, price) VALUES (579, 'Ford', 'Probe', '6.60');
INSERT INTO car (id, make, model, price) VALUES (580, 'Honda', 'Accord', '4.12');
INSERT INTO car (id, make, model, price) VALUES (581, 'Ford', 'Mustang', '4.60');
INSERT INTO car (id, make, model, price) VALUES (582, 'Isuzu', 'Ascender', '2.58');
INSERT INTO car (id, make, model, price) VALUES (583, 'Audi', '80/90', '1.47');
INSERT INTO car (id, make, model, price) VALUES (584, 'Chevrolet', 'Cavalier', '5.58');
INSERT INTO car (id, make, model, price) VALUES (585, 'Audi', 'Q5', '5.63');
INSERT INTO car (id, make, model, price) VALUES (586, 'Maybach', '62', '1.64');
INSERT INTO car (id, make, model, price) VALUES (587, 'Lotus', 'Exige', '5.52');
INSERT INTO car (id, make, model, price) VALUES (588, 'Mitsubishi', 'GTO', '9.41');
INSERT INTO car (id, make, model, price) VALUES (589, 'Aston Martin', 'DB9', '7.65');
INSERT INTO car (id, make, model, price) VALUES (590, 'Chevrolet', 'Camaro', '4.76');
INSERT INTO car (id, make, model, price) VALUES (591, 'Chevrolet', 'Silverado', '1.96');
INSERT INTO car (id, make, model, price) VALUES (592, 'Ford', 'Econoline E150', '0.18');
INSERT INTO car (id, make, model, price) VALUES (593, 'Saab', '9-3', '3.35');
INSERT INTO car (id, make, model, price) VALUES (594, 'Toyota', 'Land Cruiser', '1.81');
INSERT INTO car (id, make, model, price) VALUES (595, 'Hyundai', 'Equus', '4.25');
INSERT INTO car (id, make, model, price) VALUES (596, 'Mercedes-Benz', 'SL-Class', '8.63');
INSERT INTO car (id, make, model, price) VALUES (597, 'Oldsmobile', 'Bravada', '3.71');
INSERT INTO car (id, make, model, price) VALUES (598, 'Chevrolet', 'Express 3500', '9.95');
INSERT INTO car (id, make, model, price) VALUES (599, 'Pontiac', 'G6', '1.68');
INSERT INTO car (id, make, model, price) VALUES (600, 'Dodge', 'Viper', '7.27');
INSERT INTO car (id, make, model, price) VALUES (601, 'Eagle', 'Summit', '5.72');
INSERT INTO car (id, make, model, price) VALUES (602, 'Ford', 'EXP', '5.60');
INSERT INTO car (id, make, model, price) VALUES (603, 'Ford', 'LTD', '7.08');
INSERT INTO car (id, make, model, price) VALUES (604, 'Volkswagen', 'Passat', '8.77');
INSERT INTO car (id, make, model, price) VALUES (605, 'Dodge', 'Dakota', '6.81');
INSERT INTO car (id, make, model, price) VALUES (606, 'Mercedes-Benz', 'CL-Class', '9.99');
INSERT INTO car (id, make, model, price) VALUES (607, 'Dodge', 'Ram Van 2500', '1.10');
INSERT INTO car (id, make, model, price) VALUES (608, 'Ford', 'Ranger', '9.43');
INSERT INTO car (id, make, model, price) VALUES (609, 'Ford', 'E-Series', '6.67');
INSERT INTO car (id, make, model, price) VALUES (610, 'Chevrolet', 'Camaro', '9.33');
INSERT INTO car (id, make, model, price) VALUES (611, 'Volkswagen', 'Passat', '8.79');
INSERT INTO car (id, make, model, price) VALUES (612, 'Honda', 'Accord', '8.97');
INSERT INTO car (id, make, model, price) VALUES (613, 'Ford', 'Galaxie', '6.77');
INSERT INTO car (id, make, model, price) VALUES (614, 'Ford', 'Escape', '8.29');
INSERT INTO car (id, make, model, price) VALUES (615, 'GMC', 'Envoy', '5.47');
INSERT INTO car (id, make, model, price) VALUES (616, 'Porsche', '911', '5.84');
INSERT INTO car (id, make, model, price) VALUES (617, 'Mercury', 'Sable', '9.59');
INSERT INTO car (id, make, model, price) VALUES (618, 'Cadillac', 'SRX', '1.86');
INSERT INTO car (id, make, model, price) VALUES (619, 'Eagle', 'Summit', '3.14');
INSERT INTO car (id, make, model, price) VALUES (620, 'Dodge', 'Challenger', '3.66');
INSERT INTO car (id, make, model, price) VALUES (621, 'Mitsubishi', 'Challenger', '5.19');
INSERT INTO car (id, make, model, price) VALUES (622, 'Mazda', 'RX-8', '4.68');
INSERT INTO car (id, make, model, price) VALUES (623, 'Mitsubishi', 'Expo', '0.27');
INSERT INTO car (id, make, model, price) VALUES (624, 'Ford', 'E-Series', '1.93');
INSERT INTO car (id, make, model, price) VALUES (625, 'Plymouth', 'Colt', '0.51');
INSERT INTO car (id, make, model, price) VALUES (626, 'Kia', 'Sedona', '9.89');
INSERT INTO car (id, make, model, price) VALUES (627, 'Plymouth', 'Acclaim', '7.41');
INSERT INTO car (id, make, model, price) VALUES (628, 'Saab', '9-5', '9.23');
INSERT INTO car (id, make, model, price) VALUES (629, 'Ferrari', '430 Scuderia', '3.69');
INSERT INTO car (id, make, model, price) VALUES (630, 'Mitsubishi', 'Mirage', '7.10');
INSERT INTO car (id, make, model, price) VALUES (631, 'Pontiac', 'Grand Am', '9.18');
INSERT INTO car (id, make, model, price) VALUES (632, 'Geo', 'Tracker', '6.77');
INSERT INTO car (id, make, model, price) VALUES (633, 'Lincoln', 'Navigator', '7.17');
INSERT INTO car (id, make, model, price) VALUES (634, 'Chrysler', 'Crossfire', '5.23');
INSERT INTO car (id, make, model, price) VALUES (635, 'Suzuki', 'XL-7', '0.64');
INSERT INTO car (id, make, model, price) VALUES (636, 'Mercedes-Benz', 'SLK-Class', '0.18');
INSERT INTO car (id, make, model, price) VALUES (637, 'Honda', 'Accord', '8.60');
INSERT INTO car (id, make, model, price) VALUES (638, 'Chevrolet', 'Express 3500', '3.82');
INSERT INTO car (id, make, model, price) VALUES (639, 'Saab', '9000', '2.32');
INSERT INTO car (id, make, model, price) VALUES (640, 'Mercedes-Benz', 'CL-Class', '1.00');
INSERT INTO car (id, make, model, price) VALUES (641, 'Chrysler', 'PT Cruiser', '5.67');
INSERT INTO car (id, make, model, price) VALUES (642, 'Chrysler', 'Town & Country', '3.91');
INSERT INTO car (id, make, model, price) VALUES (643, 'Mercedes-Benz', 'CL-Class', '4.24');
INSERT INTO car (id, make, model, price) VALUES (644, 'Lexus', 'HS', '1.09');
INSERT INTO car (id, make, model, price) VALUES (645, 'Lexus', 'RX', '0.05');
INSERT INTO car (id, make, model, price) VALUES (646, 'Mitsubishi', 'L300', '5.78');
INSERT INTO car (id, make, model, price) VALUES (647, 'Honda', 'Odyssey', '8.38');
INSERT INTO car (id, make, model, price) VALUES (648, 'Mercedes-Benz', 'W201', '9.50');
INSERT INTO car (id, make, model, price) VALUES (649, 'Hyundai', 'Tucson', '3.35');
INSERT INTO car (id, make, model, price) VALUES (650, 'Chevrolet', 'Silverado 2500', '8.44');
INSERT INTO car (id, make, model, price) VALUES (651, 'Hyundai', 'Santa Fe', '7.53');
INSERT INTO car (id, make, model, price) VALUES (652, 'Cadillac', 'Seville', '0.83');
INSERT INTO car (id, make, model, price) VALUES (653, 'Audi', '5000CS Quattro', '7.32');
INSERT INTO car (id, make, model, price) VALUES (654, 'Chrysler', 'Fifth Ave', '7.27');
INSERT INTO car (id, make, model, price) VALUES (655, 'Infiniti', 'QX', '3.49');
INSERT INTO car (id, make, model, price) VALUES (656, 'Ford', 'E250', '5.02');
INSERT INTO car (id, make, model, price) VALUES (657, 'Infiniti', 'QX', '9.63');
INSERT INTO car (id, make, model, price) VALUES (658, 'Hyundai', 'XG300', '0.28');
INSERT INTO car (id, make, model, price) VALUES (659, 'Hyundai', 'Accent', '9.02');
INSERT INTO car (id, make, model, price) VALUES (660, 'Chrysler', 'Cirrus', '8.79');
INSERT INTO car (id, make, model, price) VALUES (661, 'Buick', 'Riviera', '6.86');
INSERT INTO car (id, make, model, price) VALUES (662, 'Acura', 'Legend', '9.18');
INSERT INTO car (id, make, model, price) VALUES (663, 'Saab', '9-5', '8.21');
INSERT INTO car (id, make, model, price) VALUES (664, 'GMC', '3500 Club Coupe', '2.55');
INSERT INTO car (id, make, model, price) VALUES (665, 'Chevrolet', 'HHR', '8.91');
INSERT INTO car (id, make, model, price) VALUES (666, 'Mitsubishi', 'Outlander Sport', '7.40');
INSERT INTO car (id, make, model, price) VALUES (667, 'Mitsubishi', 'GTO', '9.62');
INSERT INTO car (id, make, model, price) VALUES (668, 'Chevrolet', 'Corvette', '8.24');
INSERT INTO car (id, make, model, price) VALUES (669, 'GMC', '3500 Club Coupe', '0.34');
INSERT INTO car (id, make, model, price) VALUES (670, 'Dodge', 'Viper', '9.01');
INSERT INTO car (id, make, model, price) VALUES (671, 'Subaru', 'Loyale', '0.76');
INSERT INTO car (id, make, model, price) VALUES (672, 'Ford', 'Bronco II', '1.43');
INSERT INTO car (id, make, model, price) VALUES (673, 'Chevrolet', '2500', '8.06');
INSERT INTO car (id, make, model, price) VALUES (674, 'Ford', 'F450', '3.71');
INSERT INTO car (id, make, model, price) VALUES (675, 'Rolls-Royce', 'Phantom', '1.70');
INSERT INTO car (id, make, model, price) VALUES (676, 'GMC', 'Sonoma', '6.34');
INSERT INTO car (id, make, model, price) VALUES (677, 'Volkswagen', 'Phaeton', '4.08');
INSERT INTO car (id, make, model, price) VALUES (678, 'Chevrolet', '3500', '2.62');
INSERT INTO car (id, make, model, price) VALUES (679, 'Honda', 'CR-X', '2.28');
INSERT INTO car (id, make, model, price) VALUES (680, 'Chevrolet', 'Silverado 2500', '1.45');
INSERT INTO car (id, make, model, price) VALUES (681, 'Isuzu', 'Trooper', '1.97');
INSERT INTO car (id, make, model, price) VALUES (682, 'Peugeot', '207', '5.00');
INSERT INTO car (id, make, model, price) VALUES (683, 'Volkswagen', 'CC', '4.61');
INSERT INTO car (id, make, model, price) VALUES (684, 'Mitsubishi', 'Montero Sport', '3.96');
INSERT INTO car (id, make, model, price) VALUES (685, 'Hyundai', 'Entourage', '1.32');
INSERT INTO car (id, make, model, price) VALUES (686, 'Dodge', 'D250 Club', '3.10');
INSERT INTO car (id, make, model, price) VALUES (687, 'BMW', '5 Series', '6.59');
INSERT INTO car (id, make, model, price) VALUES (688, 'BMW', '760', '1.95');
INSERT INTO car (id, make, model, price) VALUES (689, 'Chevrolet', 'Venture', '5.43');
INSERT INTO car (id, make, model, price) VALUES (690, 'Chrysler', '200', '4.83');
INSERT INTO car (id, make, model, price) VALUES (691, 'Chevrolet', 'Suburban 2500', '3.36');
INSERT INTO car (id, make, model, price) VALUES (692, 'GMC', 'Rally Wagon 2500', '9.36');
INSERT INTO car (id, make, model, price) VALUES (693, 'Chevrolet', 'Equinox', '2.53');
INSERT INTO car (id, make, model, price) VALUES (694, 'GMC', 'Safari', '0.67');
INSERT INTO car (id, make, model, price) VALUES (695, 'Mercedes-Benz', 'M-Class', '7.65');
INSERT INTO car (id, make, model, price) VALUES (696, 'Kia', 'Carens', '1.94');
INSERT INTO car (id, make, model, price) VALUES (697, 'Kia', 'Optima', '7.71');
INSERT INTO car (id, make, model, price) VALUES (698, 'Saturn', 'Outlook', '2.32');
INSERT INTO car (id, make, model, price) VALUES (699, 'Mitsubishi', 'Pajero', '7.84');
INSERT INTO car (id, make, model, price) VALUES (700, 'Jaguar', 'XJ Series', '0.80');
INSERT INTO car (id, make, model, price) VALUES (701, 'Audi', '90', '4.02');
INSERT INTO car (id, make, model, price) VALUES (702, 'Honda', 'Accord', '9.63');
INSERT INTO car (id, make, model, price) VALUES (703, 'Pontiac', 'Sunbird', '0.73');
INSERT INTO car (id, make, model, price) VALUES (704, 'Saab', '9000', '7.55');
INSERT INTO car (id, make, model, price) VALUES (705, 'Audi', '4000s', '1.60');
INSERT INTO car (id, make, model, price) VALUES (706, 'GMC', 'Jimmy', '9.55');
INSERT INTO car (id, make, model, price) VALUES (707, 'Ford', 'Thunderbird', '7.98');
INSERT INTO car (id, make, model, price) VALUES (708, 'Lexus', 'RX', '0.26');
INSERT INTO car (id, make, model, price) VALUES (709, 'Ford', 'E-Series', '5.81');
INSERT INTO car (id, make, model, price) VALUES (710, 'Honda', 'CR-V', '7.29');
INSERT INTO car (id, make, model, price) VALUES (711, 'GMC', 'Canyon', '5.97');
INSERT INTO car (id, make, model, price) VALUES (712, 'Chevrolet', 'Camaro', '9.09');
INSERT INTO car (id, make, model, price) VALUES (713, 'Dodge', 'Ram 1500', '4.53');
INSERT INTO car (id, make, model, price) VALUES (714, 'Dodge', 'Avenger', '8.35');
INSERT INTO car (id, make, model, price) VALUES (715, 'Toyota', 'MR2', '0.42');
INSERT INTO car (id, make, model, price) VALUES (716, 'Aston Martin', 'V8 Vantage S', '4.06');
INSERT INTO car (id, make, model, price) VALUES (717, 'Chevrolet', 'Corvette', '9.92');
INSERT INTO car (id, make, model, price) VALUES (718, 'GMC', 'Savana', '3.55');
INSERT INTO car (id, make, model, price) VALUES (719, 'Mitsubishi', 'Mirage', '8.73');
INSERT INTO car (id, make, model, price) VALUES (720, 'Lamborghini', 'Murciélago', '9.58');
INSERT INTO car (id, make, model, price) VALUES (721, 'GMC', 'Yukon XL 1500', '6.63');
INSERT INTO car (id, make, model, price) VALUES (722, 'Volvo', '940', '3.74');
INSERT INTO car (id, make, model, price) VALUES (723, 'Chevrolet', 'Tahoe', '6.53');
INSERT INTO car (id, make, model, price) VALUES (724, 'Chrysler', 'Sebring', '8.96');
INSERT INTO car (id, make, model, price) VALUES (725, 'GMC', '2500 Club Coupe', '4.49');
INSERT INTO car (id, make, model, price) VALUES (726, 'Pontiac', 'Grand Am', '1.43');
INSERT INTO car (id, make, model, price) VALUES (727, 'Volkswagen', 'GTI', '6.53');
INSERT INTO car (id, make, model, price) VALUES (728, 'Mercedes-Benz', 'Sprinter 2500', '1.30');
INSERT INTO car (id, make, model, price) VALUES (729, 'Dodge', 'Ram 3500', '3.71');
INSERT INTO car (id, make, model, price) VALUES (730, 'Ford', 'Probe', '5.16');
INSERT INTO car (id, make, model, price) VALUES (731, 'Eagle', 'Vision', '6.42');
INSERT INTO car (id, make, model, price) VALUES (732, 'Mercury', 'Villager', '6.53');
INSERT INTO car (id, make, model, price) VALUES (733, 'Subaru', 'Alcyone SVX', '7.25');
INSERT INTO car (id, make, model, price) VALUES (734, 'Suzuki', 'Sidekick', '1.44');
INSERT INTO car (id, make, model, price) VALUES (735, 'BMW', '8 Series', '9.02');
INSERT INTO car (id, make, model, price) VALUES (736, 'Dodge', 'Ram', '6.51');
INSERT INTO car (id, make, model, price) VALUES (737, 'Cadillac', 'Eldorado', '3.07');
INSERT INTO car (id, make, model, price) VALUES (738, 'Audi', 'S8', '8.96');
INSERT INTO car (id, make, model, price) VALUES (739, 'Buick', 'Park Avenue', '0.67');
INSERT INTO car (id, make, model, price) VALUES (740, 'Oldsmobile', '98', '9.07');
INSERT INTO car (id, make, model, price) VALUES (741, 'Kia', 'Forte', '0.60');
INSERT INTO car (id, make, model, price) VALUES (742, 'Toyota', 'Previa', '5.61');
INSERT INTO car (id, make, model, price) VALUES (743, 'Oldsmobile', 'Bravada', '4.95');
INSERT INTO car (id, make, model, price) VALUES (744, 'Ford', 'E-Series', '3.97');
INSERT INTO car (id, make, model, price) VALUES (745, 'Volkswagen', 'Routan', '5.01');
INSERT INTO car (id, make, model, price) VALUES (746, 'GMC', '2500', '4.87');
INSERT INTO car (id, make, model, price) VALUES (747, 'Ford', 'Bronco', '0.72');
INSERT INTO car (id, make, model, price) VALUES (748, 'Volkswagen', 'GTI', '4.37');
INSERT INTO car (id, make, model, price) VALUES (749, 'Oldsmobile', '88', '8.87');
INSERT INTO car (id, make, model, price) VALUES (750, 'Buick', 'Coachbuilder', '8.77');
INSERT INTO car (id, make, model, price) VALUES (751, 'Toyota', '4Runner', '4.38');
INSERT INTO car (id, make, model, price) VALUES (752, 'Pontiac', 'Trans Sport', '7.87');
INSERT INTO car (id, make, model, price) VALUES (753, 'Chevrolet', 'Camaro', '6.40');
INSERT INTO car (id, make, model, price) VALUES (754, 'Pontiac', 'Grand Prix', '9.64');
INSERT INTO car (id, make, model, price) VALUES (755, 'GMC', 'Vandura 1500', '2.91');
INSERT INTO car (id, make, model, price) VALUES (756, 'Chevrolet', 'Caprice', '6.89');
INSERT INTO car (id, make, model, price) VALUES (757, 'Chevrolet', 'Blazer', '5.67');
INSERT INTO car (id, make, model, price) VALUES (758, 'Lexus', 'RX Hybrid', '5.52');
INSERT INTO car (id, make, model, price) VALUES (759, 'Honda', 'CR-V', '3.49');
INSERT INTO car (id, make, model, price) VALUES (760, 'Chevrolet', 'Corvette', '2.52');
INSERT INTO car (id, make, model, price) VALUES (761, 'Ford', 'Escort', '8.95');
INSERT INTO car (id, make, model, price) VALUES (762, 'Volkswagen', 'Golf', '4.53');
INSERT INTO car (id, make, model, price) VALUES (763, 'Ford', 'Mustang', '5.36');
INSERT INTO car (id, make, model, price) VALUES (764, 'Honda', 'Element', '9.00');
INSERT INTO car (id, make, model, price) VALUES (765, 'Mazda', 'Mazda3', '2.71');
INSERT INTO car (id, make, model, price) VALUES (766, 'Mazda', 'CX-9', '1.13');
INSERT INTO car (id, make, model, price) VALUES (767, 'Ford', 'Flex', '5.17');
INSERT INTO car (id, make, model, price) VALUES (768, 'Nissan', 'Titan', '9.92');
INSERT INTO car (id, make, model, price) VALUES (769, 'Nissan', 'Rogue', '2.08');
INSERT INTO car (id, make, model, price) VALUES (770, 'Dodge', 'Ram 2500', '7.61');
INSERT INTO car (id, make, model, price) VALUES (771, 'Dodge', 'Omni', '0.55');
INSERT INTO car (id, make, model, price) VALUES (772, 'Subaru', 'Legacy', '4.64');
INSERT INTO car (id, make, model, price) VALUES (773, 'Cadillac', 'Escalade EXT', '4.51');
INSERT INTO car (id, make, model, price) VALUES (774, 'Toyota', 'MR2', '4.59');
INSERT INTO car (id, make, model, price) VALUES (775, 'Geo', 'Tracker', '3.76');
INSERT INTO car (id, make, model, price) VALUES (776, 'Chrysler', '300', '5.79');
INSERT INTO car (id, make, model, price) VALUES (777, 'Lexus', 'LS Hybrid', '6.13');
INSERT INTO car (id, make, model, price) VALUES (778, 'Chevrolet', 'Cobalt', '3.54');
INSERT INTO car (id, make, model, price) VALUES (779, 'Honda', 'Accord', '0.00');
INSERT INTO car (id, make, model, price) VALUES (780, 'Chevrolet', 'Camaro', '8.89');
INSERT INTO car (id, make, model, price) VALUES (781, 'Daewoo', 'Lanos', '5.92');
INSERT INTO car (id, make, model, price) VALUES (782, 'GMC', 'Canyon', '3.17');
INSERT INTO car (id, make, model, price) VALUES (783, 'Audi', 'Quattro', '3.97');
INSERT INTO car (id, make, model, price) VALUES (784, 'Ford', 'Falcon', '6.04');
INSERT INTO car (id, make, model, price) VALUES (785, 'Mazda', 'CX-9', '0.26');
INSERT INTO car (id, make, model, price) VALUES (786, 'Dodge', 'Ram Van B250', '6.10');
INSERT INTO car (id, make, model, price) VALUES (787, 'Pontiac', 'Grand Am', '3.11');
INSERT INTO car (id, make, model, price) VALUES (788, 'Land Rover', 'Discovery', '0.50');
INSERT INTO car (id, make, model, price) VALUES (789, 'Cadillac', 'Eldorado', '0.02');
INSERT INTO car (id, make, model, price) VALUES (790, 'Mercury', 'Cougar', '5.38');
INSERT INTO car (id, make, model, price) VALUES (791, 'Lotus', 'Exige', '4.62');
INSERT INTO car (id, make, model, price) VALUES (792, 'Hyundai', 'Azera', '5.39');
INSERT INTO car (id, make, model, price) VALUES (793, 'Subaru', 'Forester', '2.89');
INSERT INTO car (id, make, model, price) VALUES (794, 'Chevrolet', 'Express 1500', '9.20');
INSERT INTO car (id, make, model, price) VALUES (795, 'Subaru', 'Loyale', '1.27');
INSERT INTO car (id, make, model, price) VALUES (796, 'Isuzu', 'Trooper', '8.73');
INSERT INTO car (id, make, model, price) VALUES (797, 'Nissan', 'Murano', '7.32');
INSERT INTO car (id, make, model, price) VALUES (798, 'Studebaker', 'Avanti', '0.51');
INSERT INTO car (id, make, model, price) VALUES (799, 'Dodge', 'Caravan', '8.45');
INSERT INTO car (id, make, model, price) VALUES (800, 'Cadillac', 'STS', '7.32');
INSERT INTO car (id, make, model, price) VALUES (801, 'Lexus', 'IS-F', '0.93');
INSERT INTO car (id, make, model, price) VALUES (802, 'GMC', 'Savana Cargo Van', '8.63');
INSERT INTO car (id, make, model, price) VALUES (803, 'Hyundai', 'Veracruz', '6.89');
INSERT INTO car (id, make, model, price) VALUES (804, 'Ford', 'Freestyle', '1.91');
INSERT INTO car (id, make, model, price) VALUES (805, 'Chrysler', 'Town & Country', '1.29');
INSERT INTO car (id, make, model, price) VALUES (806, 'Lexus', 'IS', '5.69');
INSERT INTO car (id, make, model, price) VALUES (807, 'Audi', '200', '7.75');
INSERT INTO car (id, make, model, price) VALUES (808, 'Nissan', 'Frontier', '9.55');
INSERT INTO car (id, make, model, price) VALUES (809, 'Honda', 'Odyssey', '4.11');
INSERT INTO car (id, make, model, price) VALUES (810, 'Infiniti', 'M', '6.72');
INSERT INTO car (id, make, model, price) VALUES (811, 'Mercedes-Benz', 'E-Class', '5.62');
INSERT INTO car (id, make, model, price) VALUES (812, 'BMW', 'Z8', '5.35');
INSERT INTO car (id, make, model, price) VALUES (813, 'Toyota', 'RAV4', '9.84');
INSERT INTO car (id, make, model, price) VALUES (814, 'Ford', 'F-Series', '1.07');
INSERT INTO car (id, make, model, price) VALUES (815, 'Mercury', 'Grand Marquis', '3.70');
INSERT INTO car (id, make, model, price) VALUES (816, 'Chevrolet', 'Suburban 2500', '9.58');
INSERT INTO car (id, make, model, price) VALUES (817, 'Jaguar', 'XJ Series', '9.22');
INSERT INTO car (id, make, model, price) VALUES (818, 'Volkswagen', 'Rabbit', '5.33');
INSERT INTO car (id, make, model, price) VALUES (819, 'Toyota', 'Celica', '0.76');
INSERT INTO car (id, make, model, price) VALUES (820, 'Audi', 'A8', '3.81');
INSERT INTO car (id, make, model, price) VALUES (821, 'Dodge', 'Ram 3500', '3.86');
INSERT INTO car (id, make, model, price) VALUES (822, 'Buick', 'Rendezvous', '6.78');
INSERT INTO car (id, make, model, price) VALUES (823, 'Oldsmobile', 'Aurora', '5.24');
INSERT INTO car (id, make, model, price) VALUES (824, 'GMC', 'Sierra 1500', '1.06');
INSERT INTO car (id, make, model, price) VALUES (825, 'Chrysler', '300M', '6.18');
INSERT INTO car (id, make, model, price) VALUES (826, 'Ford', 'Festiva', '9.51');
INSERT INTO car (id, make, model, price) VALUES (827, 'GMC', 'Sonoma Club Coupe', '7.69');
INSERT INTO car (id, make, model, price) VALUES (828, 'Ford', 'Windstar', '3.49');
INSERT INTO car (id, make, model, price) VALUES (829, 'Toyota', 'Matrix', '8.55');
INSERT INTO car (id, make, model, price) VALUES (830, 'Buick', 'LeSabre', '1.68');
INSERT INTO car (id, make, model, price) VALUES (831, 'Mitsubishi', 'Mirage', '2.99');
INSERT INTO car (id, make, model, price) VALUES (832, 'Chevrolet', 'Astro', '8.50');
INSERT INTO car (id, make, model, price) VALUES (833, 'Jeep', 'Commander', '8.62');
INSERT INTO car (id, make, model, price) VALUES (834, 'Ford', 'Club Wagon', '6.60');
INSERT INTO car (id, make, model, price) VALUES (835, 'Ford', 'Freestar', '4.04');
INSERT INTO car (id, make, model, price) VALUES (836, 'Dodge', 'Ram Van 2500', '9.10');
INSERT INTO car (id, make, model, price) VALUES (837, 'Mitsubishi', 'GTO', '3.67');
INSERT INTO car (id, make, model, price) VALUES (838, 'Chevrolet', 'Malibu', '3.30');
INSERT INTO car (id, make, model, price) VALUES (839, 'Audi', 'S4', '8.87');
INSERT INTO car (id, make, model, price) VALUES (840, 'Nissan', 'Cube', '4.22');
INSERT INTO car (id, make, model, price) VALUES (841, 'Buick', 'Regal', '3.77');
INSERT INTO car (id, make, model, price) VALUES (842, 'Nissan', '350Z', '4.99');
INSERT INTO car (id, make, model, price) VALUES (843, 'Hyundai', 'Tucson', '4.16');
INSERT INTO car (id, make, model, price) VALUES (844, 'Mazda', 'B-Series', '8.27');
INSERT INTO car (id, make, model, price) VALUES (845, 'Ford', 'Econoline E150', '2.29');
INSERT INTO car (id, make, model, price) VALUES (846, 'Jaguar', 'XJ Series', '7.46');
INSERT INTO car (id, make, model, price) VALUES (847, 'Dodge', 'Viper', '4.58');
INSERT INTO car (id, make, model, price) VALUES (848, 'Volkswagen', 'Type 2', '7.40');
INSERT INTO car (id, make, model, price) VALUES (849, 'Honda', 'FCX Clarity', '3.17');
INSERT INTO car (id, make, model, price) VALUES (850, 'Nissan', 'Altima', '9.09');
INSERT INTO car (id, make, model, price) VALUES (851, 'Buick', 'Park Avenue', '8.95');
INSERT INTO car (id, make, model, price) VALUES (852, 'Lexus', 'ES', '0.04');
INSERT INTO car (id, make, model, price) VALUES (853, 'BMW', '745', '0.24');
INSERT INTO car (id, make, model, price) VALUES (854, 'GMC', 'Yukon', '4.16');
INSERT INTO car (id, make, model, price) VALUES (855, 'Lincoln', 'Continental', '3.56');
INSERT INTO car (id, make, model, price) VALUES (856, 'Toyota', 'Sienna', '5.84');
INSERT INTO car (id, make, model, price) VALUES (857, 'Nissan', '370Z', '1.06');
INSERT INTO car (id, make, model, price) VALUES (858, 'Pontiac', 'G6', '0.81');
INSERT INTO car (id, make, model, price) VALUES (859, 'BMW', 'M3', '0.17');
INSERT INTO car (id, make, model, price) VALUES (860, 'Ford', 'Expedition EL', '8.92');
INSERT INTO car (id, make, model, price) VALUES (861, 'Jaguar', 'XK', '5.29');
INSERT INTO car (id, make, model, price) VALUES (862, 'Ford', 'F150', '6.55');
INSERT INTO car (id, make, model, price) VALUES (863, 'Honda', 'Prelude', '6.28');
INSERT INTO car (id, make, model, price) VALUES (864, 'BMW', 'Z8', '3.95');
INSERT INTO car (id, make, model, price) VALUES (865, 'Toyota', 'Solara', '5.96');
INSERT INTO car (id, make, model, price) VALUES (866, 'Lincoln', 'Town Car', '4.74');
INSERT INTO car (id, make, model, price) VALUES (867, 'Mercury', 'Grand Marquis', '5.45');
INSERT INTO car (id, make, model, price) VALUES (868, 'Honda', 'Pilot', '7.85');
INSERT INTO car (id, make, model, price) VALUES (869, 'Maybach', '57', '8.64');
INSERT INTO car (id, make, model, price) VALUES (870, 'Kia', 'Sportage', '5.52');
INSERT INTO car (id, make, model, price) VALUES (871, 'Mitsubishi', 'Outlander', '7.19');
INSERT INTO car (id, make, model, price) VALUES (872, 'Volvo', 'XC70', '9.34');
INSERT INTO car (id, make, model, price) VALUES (873, 'Mazda', 'Mazda3', '8.97');
INSERT INTO car (id, make, model, price) VALUES (874, 'Ford', 'E-Series', '3.25');
INSERT INTO car (id, make, model, price) VALUES (875, 'Oldsmobile', 'Cutlass Supreme', '9.84');
INSERT INTO car (id, make, model, price) VALUES (876, 'Ford', 'E-Series', '6.12');
INSERT INTO car (id, make, model, price) VALUES (877, 'Toyota', '4Runner', '9.66');
INSERT INTO car (id, make, model, price) VALUES (878, 'Volvo', 'C70', '7.40');
INSERT INTO car (id, make, model, price) VALUES (879, 'Mitsubishi', 'Challenger', '8.30');
INSERT INTO car (id, make, model, price) VALUES (880, 'Jeep', 'Wrangler', '6.18');
INSERT INTO car (id, make, model, price) VALUES (881, 'Hyundai', 'Azera', '9.71');
INSERT INTO car (id, make, model, price) VALUES (882, 'Land Rover', 'Range Rover', '9.87');
INSERT INTO car (id, make, model, price) VALUES (883, 'Mazda', 'CX-9', '4.68');
INSERT INTO car (id, make, model, price) VALUES (884, 'Mitsubishi', 'Lancer', '4.76');
INSERT INTO car (id, make, model, price) VALUES (885, 'Mitsubishi', 'Pajero', '3.20');
INSERT INTO car (id, make, model, price) VALUES (886, 'Mercury', 'Villager', '5.64');
INSERT INTO car (id, make, model, price) VALUES (887, 'Acura', 'MDX', '8.97');
INSERT INTO car (id, make, model, price) VALUES (888, 'Ford', 'E-Series', '3.23');
INSERT INTO car (id, make, model, price) VALUES (889, 'Saturn', 'VUE', '8.58');
INSERT INTO car (id, make, model, price) VALUES (890, 'BMW', 'M', '4.01');
INSERT INTO car (id, make, model, price) VALUES (891, 'Maserati', 'Quattroporte', '9.53');
INSERT INTO car (id, make, model, price) VALUES (892, 'Maybach', 'Landaulet', '1.22');
INSERT INTO car (id, make, model, price) VALUES (893, 'Mazda', 'Familia', '1.13');
INSERT INTO car (id, make, model, price) VALUES (894, 'Mitsubishi', 'Pajero', '8.48');
INSERT INTO car (id, make, model, price) VALUES (895, 'Chevrolet', 'Astro', '9.78');
INSERT INTO car (id, make, model, price) VALUES (896, 'Chevrolet', 'TrailBlazer', '6.09');
INSERT INTO car (id, make, model, price) VALUES (897, 'Audi', 'A4', '8.02');
INSERT INTO car (id, make, model, price) VALUES (898, 'GMC', 'Savana 1500', '8.38');
INSERT INTO car (id, make, model, price) VALUES (899, 'Mercedes-Benz', 'R-Class', '2.69');
INSERT INTO car (id, make, model, price) VALUES (900, 'Chevrolet', 'Silverado 1500', '6.52');
INSERT INTO car (id, make, model, price) VALUES (901, 'Oldsmobile', 'Silhouette', '0.57');
INSERT INTO car (id, make, model, price) VALUES (902, 'Toyota', 'TundraMax', '2.08');
INSERT INTO car (id, make, model, price) VALUES (903, 'Mazda', '929', '9.12');
INSERT INTO car (id, make, model, price) VALUES (904, 'Mercedes-Benz', 'G-Class', '0.55');
INSERT INTO car (id, make, model, price) VALUES (905, 'Pontiac', 'G5', '0.12');
INSERT INTO car (id, make, model, price) VALUES (906, 'Chevrolet', '1500', '4.49');
INSERT INTO car (id, make, model, price) VALUES (907, 'Dodge', 'Ram 3500', '9.62');
INSERT INTO car (id, make, model, price) VALUES (908, 'Pontiac', 'Bonneville', '0.51');
INSERT INTO car (id, make, model, price) VALUES (909, 'Suzuki', 'Samurai', '7.45');
INSERT INTO car (id, make, model, price) VALUES (910, 'Toyota', '4Runner', '7.32');
INSERT INTO car (id, make, model, price) VALUES (911, 'Mazda', 'RX-7', '5.01');
INSERT INTO car (id, make, model, price) VALUES (912, 'Porsche', '944', '7.41');
INSERT INTO car (id, make, model, price) VALUES (913, 'BMW', '8 Series', '4.81');
INSERT INTO car (id, make, model, price) VALUES (914, 'Buick', 'Rendezvous', '3.53');
INSERT INTO car (id, make, model, price) VALUES (915, 'Chevrolet', 'Express', '9.44');
INSERT INTO car (id, make, model, price) VALUES (916, 'Buick', 'Riviera', '3.03');
INSERT INTO car (id, make, model, price) VALUES (917, 'Pontiac', 'Grand Prix', '9.27');
INSERT INTO car (id, make, model, price) VALUES (918, 'Lincoln', 'Navigator', '7.22');
INSERT INTO car (id, make, model, price) VALUES (919, 'Ford', 'Explorer Sport Trac', '9.27');
INSERT INTO car (id, make, model, price) VALUES (920, 'Mercedes-Benz', 'C-Class', '7.01');
INSERT INTO car (id, make, model, price) VALUES (921, 'Chevrolet', 'Corvette', '7.49');
INSERT INTO car (id, make, model, price) VALUES (922, 'Lamborghini', 'Gallardo', '1.69');
INSERT INTO car (id, make, model, price) VALUES (923, 'Mercedes-Benz', 'SLK55 AMG', '1.83');
INSERT INTO car (id, make, model, price) VALUES (924, 'Ford', 'E350', '2.89');
INSERT INTO car (id, make, model, price) VALUES (925, 'BMW', '3 Series', '4.62');
INSERT INTO car (id, make, model, price) VALUES (926, 'Chevrolet', 'Sportvan G30', '6.17');
INSERT INTO car (id, make, model, price) VALUES (927, 'Toyota', 'Yaris', '2.07');
INSERT INTO car (id, make, model, price) VALUES (928, 'Ford', 'Escape', '1.01');
INSERT INTO car (id, make, model, price) VALUES (929, 'Ferrari', '612 Scaglietti', '4.23');
INSERT INTO car (id, make, model, price) VALUES (930, 'Lincoln', 'MKS', '0.62');
INSERT INTO car (id, make, model, price) VALUES (931, 'Volkswagen', 'Cabriolet', '7.51');
INSERT INTO car (id, make, model, price) VALUES (932, 'Oldsmobile', '88', '5.26');
INSERT INTO car (id, make, model, price) VALUES (933, 'Ford', 'Edge', '6.38');
INSERT INTO car (id, make, model, price) VALUES (934, 'Hyundai', 'Sonata', '5.31');
INSERT INTO car (id, make, model, price) VALUES (935, 'Lamborghini', 'Diablo', '2.04');
INSERT INTO car (id, make, model, price) VALUES (936, 'Jaguar', 'XJ', '5.66');
INSERT INTO car (id, make, model, price) VALUES (937, 'Audi', 'riolet', '3.96');
INSERT INTO car (id, make, model, price) VALUES (938, 'Audi', '4000CS Quattro', '8.18');
INSERT INTO car (id, make, model, price) VALUES (939, 'Land Rover', 'Range Rover', '0.30');
INSERT INTO car (id, make, model, price) VALUES (940, 'Jaguar', 'XK Series', '4.77');
INSERT INTO car (id, make, model, price) VALUES (941, 'GMC', 'Savana 1500', '3.11');
INSERT INTO car (id, make, model, price) VALUES (942, 'Ford', 'Econoline E350', '1.94');
INSERT INTO car (id, make, model, price) VALUES (943, 'Honda', 'Insight', '2.47');
INSERT INTO car (id, make, model, price) VALUES (944, 'Chevrolet', 'Corvette', '3.68');
INSERT INTO car (id, make, model, price) VALUES (945, 'Ford', 'Escape', '0.19');
INSERT INTO car (id, make, model, price) VALUES (946, 'Porsche', 'Boxster', '5.00');
INSERT INTO car (id, make, model, price) VALUES (947, 'Ford', 'Explorer', '1.79');
INSERT INTO car (id, make, model, price) VALUES (948, 'Chevrolet', 'G-Series G30', '8.62');
INSERT INTO car (id, make, model, price) VALUES (949, 'Ford', 'E150', '4.57');
INSERT INTO car (id, make, model, price) VALUES (950, 'Maybach', '57', '2.05');
INSERT INTO car (id, make, model, price) VALUES (951, 'Chevrolet', 'Silverado 2500', '7.55');
INSERT INTO car (id, make, model, price) VALUES (952, 'Dodge', 'Ram', '6.45');
INSERT INTO car (id, make, model, price) VALUES (953, 'Chevrolet', 'Suburban 1500', '3.75');
INSERT INTO car (id, make, model, price) VALUES (954, 'Volvo', 'V50', '4.67');
INSERT INTO car (id, make, model, price) VALUES (955, 'Volkswagen', 'Touareg', '7.71');
INSERT INTO car (id, make, model, price) VALUES (956, 'Ford', 'Tempo', '7.57');
INSERT INTO car (id, make, model, price) VALUES (957, 'Toyota', 'Avalon', '4.54');
INSERT INTO car (id, make, model, price) VALUES (958, 'Volvo', 'C70', '1.64');
INSERT INTO car (id, make, model, price) VALUES (959, 'Infiniti', 'G', '5.58');
INSERT INTO car (id, make, model, price) VALUES (960, 'Plymouth', 'Sundance', '8.79');
INSERT INTO car (id, make, model, price) VALUES (961, 'Pontiac', 'Firebird', '1.31');
INSERT INTO car (id, make, model, price) VALUES (962, 'Plymouth', 'Breeze', '3.21');
INSERT INTO car (id, make, model, price) VALUES (963, 'Morgan', 'Aero 8', '4.57');
INSERT INTO car (id, make, model, price) VALUES (964, 'Mitsubishi', 'Endeavor', '2.36');
INSERT INTO car (id, make, model, price) VALUES (965, 'GMC', 'Savana 1500', '0.57');
INSERT INTO car (id, make, model, price) VALUES (966, 'Mercedes-Benz', 'SLR McLaren', '1.39');
INSERT INTO car (id, make, model, price) VALUES (967, 'Nissan', 'Pathfinder', '5.17');
INSERT INTO car (id, make, model, price) VALUES (968, 'Jaguar', 'X-Type', '4.93');
INSERT INTO car (id, make, model, price) VALUES (969, 'Bentley', 'Continental', '7.15');
INSERT INTO car (id, make, model, price) VALUES (970, 'BMW', 'M6', '4.46');
INSERT INTO car (id, make, model, price) VALUES (971, 'Chevrolet', 'Monte Carlo', '1.45');
INSERT INTO car (id, make, model, price) VALUES (972, 'Chevrolet', 'Malibu', '0.10');
INSERT INTO car (id, make, model, price) VALUES (973, 'Lincoln', 'Navigator L', '4.52');
INSERT INTO car (id, make, model, price) VALUES (974, 'Dodge', 'Ram Van 3500', '9.79');
INSERT INTO car (id, make, model, price) VALUES (975, 'Chrysler', 'Pacifica', '4.96');
INSERT INTO car (id, make, model, price) VALUES (976, 'Chrysler', 'Cirrus', '4.83');
INSERT INTO car (id, make, model, price) VALUES (977, 'Volkswagen', 'Fox', '3.64');
INSERT INTO car (id, make, model, price) VALUES (978, 'Land Rover', 'Freelander', '9.74');
INSERT INTO car (id, make, model, price) VALUES (979, 'GMC', 'Savana 1500', '8.54');
INSERT INTO car (id, make, model, price) VALUES (980, 'Lexus', 'ES', '8.41');
INSERT INTO car (id, make, model, price) VALUES (981, 'Ford', 'Focus', '4.36');
INSERT INTO car (id, make, model, price) VALUES (982, 'Honda', 'CR-V', '3.30');
INSERT INTO car (id, make, model, price) VALUES (983, 'Dodge', 'Neon', '7.08');
INSERT INTO car (id, make, model, price) VALUES (984, 'Audi', 'S8', '9.10');
INSERT INTO car (id, make, model, price) VALUES (985, 'Mazda', 'RX-7', '6.28');
INSERT INTO car (id, make, model, price) VALUES (986, 'Chevrolet', 'Colorado', '2.84');
INSERT INTO car (id, make, model, price) VALUES (987, 'Volkswagen', 'GTI', '5.01');
INSERT INTO car (id, make, model, price) VALUES (988, 'Chrysler', 'Town & Country', '6.83');
INSERT INTO car (id, make, model, price) VALUES (989, 'GMC', 'Sierra 1500', '3.76');
INSERT INTO car (id, make, model, price) VALUES (990, 'Mercedes-Benz', 'SLK-Class', '3.49');
INSERT INTO car (id, make, model, price) VALUES (991, 'Subaru', 'Impreza', '5.07');
INSERT INTO car (id, make, model, price) VALUES (992, 'Porsche', 'Boxster', '7.44');
INSERT INTO car (id, make, model, price) VALUES (993, 'Toyota', 'FJ Cruiser', '6.29');
INSERT INTO car (id, make, model, price) VALUES (994, 'Volvo', 'C30', '9.18');
INSERT INTO car (id, make, model, price) VALUES (995, 'Toyota', 'Cressida', '1.47');
INSERT INTO car (id, make, model, price) VALUES (996, 'Cadillac', 'Catera', '4.62');
INSERT INTO car (id, make, model, price) VALUES (997, 'Toyota', 'Highlander', '5.82');
INSERT INTO car (id, make, model, price) VALUES (998, 'Infiniti', 'FX', '0.64');
INSERT INTO car (id, make, model, price) VALUES (999, 'Mercedes-Benz', 'S-Class', '3.27');
INSERT INTO car (id, make, model, price) VALUES (1000, 'Jaguar', 'XJ Series', '3.58');
